<?php
/**
 * 
 * View -- of Hr/MasterController/addapptypeAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('master', array('action' => 'addempstatus')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> New Employee Status</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="estatus" class="control-label">Employee Status</label>
					<input type="text" class="form-control" name="estatus" id="estatus" size="30" placeholder="Employee Status" required> 
				</div>
				<div class="form-group">
					<label for="color" class="control-label"> Status color</label>
					<input type="text" class="form-control" name="color" id="color"  placeholder="color" required> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			estatus: {
					validators: {
						notEmpty: {
							message: 'Please provide appointment type.'
						}
					}
				},
				color: {
					validators: {
						notEmpty: {
							message: 'Please provide color.'
						}
					}
				},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
