<?php
/**
 * 
 * View -- of Hr/MasterController/adpostlevelAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('master', array('action' => 'addpostlevel')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> New Post Level</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="post_level" class="control-label">Position Level</label>
					<input type="text" class="form-control" name="post_level" id="post_level" size="30" placeholder="Position Level" required/> 
				</div>
				<div class="form-group">
					<label for="code" class="control-label">Code</label>
					<input type="text" class="form-control" name="code" id="code" size="30" placeholder="Code" required/> 
				</div>
				<div class="form-group">
					<label for="min_pay" class="control-label">Minimum Pay</label>
					<input type="text" class="form-control" name="min_pay" id="min_pay" size="30" placeholder="Minimum Pay" required/> 
				</div>
				<div class="form-group">
					<label for="increment" class="control-label">Increment</label>
					<input type="text" class="form-control" name="increment" id="increment" size="30" placeholder="Increment" required/> 
				</div>
				<div class="form-group">
					<label for="max_pay" class="control-label">Maximum Pay</label>
					<input type="text" class="form-control" name="max_pay" id="max_pay" size="30" placeholder="Maximum Pay" required/> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			post_level: {
				validators: {
					notEmpty: {
						message: 'Please provide position level.'
					}
				}
			},				
			code: {
				validators: {
					notEmpty: {
						message: 'Please provide code.'
					}
				}
			},
			min_pay: {
				validators: {
					notEmpty: {
						message: 'Please provide Minimum Pay.'
					}
				}
			},
			increment: {
				validators: {
					notEmpty: {
						message: 'Please provide Increment.'
					}
				}
			},
			max_pay: {
				validators: {
					notEmpty: {
						message: 'Please provide Maximum Pay.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
