<?php
/**
 * 
 *  Hr/MasterController/addpayheadAction
 * 
 */
?>
<form id="#form" role="form" data-toggle="validator" action="<?php echo $this->url('master', array('action' => 'addpaygroup')); ?>" enctype="multipart/form-data" method="post" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-plus"></i> Add Pay Group</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
    	<div class="panel panel-default">
    		<div class="panel-body">
				<div class="form-group">
					<label for="pay_head" class="control-label">Payhead</label>
					<select class="form-control" id="pay_head" name="pay_head" data-placeholder="Select" required>
						<option value=""></option>
						<?php 
						foreach ($this->payheads as $payhead):
						?>
							<option value="<?php echo $payhead['id'];?>" >
								<?php echo $payhead['pay_head'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
				<div class="form-group">
					<label for="group" class="control-label">Pay Group</label>
					<input type="text" name="group" id="group" class="form-control" placeholder="group" required/>
				</div>
				<div class="form-group">
					<label for="value" class="control-label">Value</label>
					<input class="form-control" name="value" id="value" placeholder="value" required >
				</div>
			</div><!-- panel-body -->
		</div><!-- panel panel-default -->	
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="reset" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>        
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			pay_head: {
				validators: {
					notEmpty: {
						message: 'Please provide pay head.'
					}
				}
			},
			value: {
				validators: {
					notEmpty: {
						message: 'Please provide value.'
					}
				}
			},
			group: {
				validators: {
					notEmpty: {
						message: 'Please provide group.'
					}		
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
