<?php
/**
 * 
 * View -- of Hr/MasterController/editleavetypeAction
 * 
 */
?>
<?php 
    foreach($this->leavetype as $leavetype):
        extract($leavetype);       
    endforeach;
?>

<form id="#form" method="post" action="<?php echo $this->url('master', array('action' => 'editleavetype', 'id' => $id)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Type of Leave</h4>
    </div>  <!-- /modal-header -->
    
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body"> 
				<div class="form-group">
					<label for="leavetype">Leave Type</label>
					<input type="text" class="form-control" name="leavetype" id="leavetype" value="<?php echo $type;?>" size="30" required> 
				</div>
				<div class="form-group">
					<label for="days">No of Days</label>
					<input type="text" class="form-control" name="total_days" id="total_days" value="<?php echo $total_days;?>" size="30"> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			leavetype: {
				validators: {
					notEmpty: {
						message: 'Please provide type of leave.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>

