<?php
/**
 * 
 * View -- of Hr/MasterController/editapptypeAction
 * 
 */
?>
<?php 
    foreach($this->apptype as $apptypes):
        extract($apptypes); 
	 endforeach;
?>

<form id="#form" method="post" action="<?php echo $this->url('master', array('action' => 'editapptype', 'id' => $id)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Appointment Type</h4>
    </div>  <!-- /modal-header -->
    
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body"> 
				<div class="form-group">
					<label for="app_type" class="control-label">Appointment Type</label>
					<input type="text" class="form-control" name="apptype" id="apptype" value="<?php echo $type_of_appointment;?>" size="30" required> 
				</div>
				<div class="form-group">
					<label for="status" class="control-label">Status</label>
					<select class="form-control" name="status" id="status" data-placeholder="Select" required > 
						<option value=""></option>
						<?php foreach($empstatus as $statu):
							$selected = ($statu['id'] == $apptypes['status'])?'selected':'';
						?>
							<option value="<?php echo $statu['id']?>" <?php echo $selected;?>>
								<?php echo $statu['status'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			post: {
                validators: {
                    notEmpty: {
                        message: 'Please provide position title.'
                    }
                }
            },
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
             








