<?php
/**
 * 
 * View -- of Hr/MasterController/editlocationAction
 * 
 */
?>
<?php 
    foreach($this->payheadtype as $payheadtype):
        extract($payheadtype);
    endforeach;
?> 
<form id="#form" method="post" action="<?php echo $this->url('master', array('action' => 'editpayheadtype', 'id' => $id)); ?>"  enctype="multipart/form-data" >                 
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="fa fa-pencil"></i> Edit Pay head Type</h4>
    </div><!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="form-group">
						<label for="head_type" class="control-label">Pay Head Type</label>
						<input class="form-control" name="payhead_type" id="payhead_type" value="<?php echo $head_type; ?>" required >
					</div>
					<div class="form-group">
						<label for="pay_head" class="control-label">Code</label>
						<input class="form-control" name="code" id="code" value="<?php echo $code; ?>" required >
					</div>
					<div class="form-group">
						<label for="deduction" class="control-label">Deduction</label>
						<?php 
							$yes = ($deduction=='1')?'checked':'';
							$no = ($deduction=='0')?'checked':'';
							  
						?>
						<div class="radio">
							<label>
								<input type="radio" name="deduction" id="deduction" value="1" <?php echo $yes; ?> required>
								Yes
							</label>
							&nbsp;&nbsp;&nbsp;
							<label>
								<input type="radio" name="deduction" id="deduction" value="0" <?php echo $no; ?> required>
								No
							</label>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<h5>Sub-Head Details</h5>
					</div>
				</div>
				<div class="row">
					<?php foreach($subheads as $subheads):?>
					<div class="form-group col-lg-6">
						<input type="hidden" name="subhead_id"; id="subhead_id" value="<?php echo $subheads['id'];?>"/>
						<label for="head_type" class="control-label">Head Type</label>
						<select class="form-control" id="head_type" name="head_type" data-placeholder="Select" required>
							<option value=""></option>
							<?php 
							foreach ($headtypes as $headtype):
							 $selected = ($subheads['headtype_id'] == $headtype['id'])? "selected":"";
							?>
								<option value="<?php echo $headtype['id'];?>" <?php echo $selected;?>>
									<?php echo $headtype['head_type'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="form-group col-lg-6">
						<label for="head" class="control-label">Head</label>
						<select class="form-control" id="head" name="head" data-placeholder="Select" required >
							<option value=""></option>
							<?php 
							$heads=$headObj->get(array('h.head_type'=> $subheads['headtype_id']));
							
							foreach ($heads as $headrow):
								$selected = ($subheads['head_id'] == $headrow['id'])? "selected":"";
							?>
								<option value="<?php echo $headrow['id'];?>" <?php echo $selected	?>>
									<?php echo $headrow['code'];?>
								</option>
							<?php endforeach;?>
						</select>
					</div>
					<?php endforeach;?>
				</div>	
				<div class="form-group">
					<label>
						<input class="ace" type="checkbox"  name="change_paystructure" id="change_paystructure" value="1" style="min-width: 90px;"></input>
						<span class="lbl"> Apply changes to Pay Structures</span>
					</label>
			    </div>
			    <div class="alert alert-warning"> 
					<strong>Warning!</strong> By Checking above checkbox the changes will be made to all the paystructures of entire employee.
				</div>	
			</div><!-- panel-body -->
        </div><!-- panel panel-default -->
    </div><!-- modal-body -->
                    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="reset" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>
    </div><!-- /modal-footer -->
</form>
<script>
$('document').ready(function(){
	$('form select').chosen({ allow_single_deselect: true });
		$("#head_type").change(function(){ 
			$('#head').load("<?php echo $this->url('ajresponse', array('action' => 'gethead')); ?>/"+ $("#head_type").val(), function() {
				$("#head").trigger('chosen:updated');
			});
		});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			head_type: {
				validators: {
					notEmpty: {
						message: 'Please provide pay head type.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>


                                

      
