<?php
/**
 * 
 * View -- of Hr/MasterController/incrementtypeAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('hr/master/partial.phtml', array('active' => 'incrementtype')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Increment Type</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->incrementtypes as $incrementype):
				?>
						<tr class="<?php echo $class; ?>">
							<td><?php echo $i++; ?> </td>
							<td><b><?php echo $incrementype['increment_type'];?></b></td>  								                            
							<?php if($this->button(1)!=""):?>
							<td><?php echo $this->button(1, $incrementype['id']);?></td>
						<?php endif;?>
						</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>
