<?php
/**
 * 
 * View -- of Hr/MsaterController/leavetypeAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('hr/master/partial.phtml', array('active' => 'leavetype')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php //echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Leave Types</th>
					<th>No. of days</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->leavetype as $leavetype):
						$class = ($i % 2 == 0)?"even gradeC":"odd gradeX";
				?>
						<tr class="<?php echo $class; ?>">
							<td><?php echo $i++; ?> </td>
							<td><b><?php echo $leavetype['type']; ?></b></td> 
							<td><?php echo $leavetype['total_days']; ?></td>                               
							<?php if($this->button(1)!=""):?>
								<td><?php echo $this->button(1, $leavetype['id']);?></td>
							<?php endif;?>    
						</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>
