<?php
/**
 * 
 * View -- of Hr/MsaterController/leavetypeAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('hr/master/partial.phtml', array('active' => 'tpn')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Employee</th>
					<th>TPN No.</th>
                    <th>GIS No.</th>
                    <th>PF No.</th>
					<th>status</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($tpn as $row):?>
						<tr>
							<td><?php echo $i++; ?> </td>
							<td><b><?php echo $this->employeeObj->getColumn($row['employee'],'full_name'); ?></b></td> 
							<td><?php echo $row['tpn']; ?></td>   
                            <td><?php echo $row['gis']; ?></td>                             
                            <td><?php echo $row['pf']; ?></td> 
							<td><?php echo isset($row['status']) ? $this->status($row['status']) : ''; ?></td>

							<?php if($this->button(1)!=""):?>
								<td><?php echo $this->button(1, $row['id']);?></td>
							<?php endif;?>    
						</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>
