<?php  $param = $this->process."-".$this->process_id; 
       $file_array = $this->attachment($param);  
	  // $stat = array('2','3'); 
       if(sizeof($file_array) > 0 ){ echo"<b> Attachments </b>";}
	  // echo '<pre>';print_r($file_array);exit;
       foreach ($file_array as $attachment): ?>
       <div class="row">
		 <div class="col-lg-8">		
           <li>
           <?php  echo  "&nbsp;".$attachment['description'] ; ?>, 
			<a href="<?php echo $this->url('upload', array('action'=>'render', 'id'=>$attachment['id'])); ?>"> 
				<span class="hidden-xs">  <?php echo $attachment['file_name']; ?></span>
				&nbsp;<i class="blue ace-icon fa fa-download bigger-120"> </i>
			</a> 
			<?php 			
			if($this->status == "2"):?>
			&nbsp;|&nbsp;
			<a href="<?php echo $this->url('upload', array('action'=>'remove', 'id'=>$attachment['id'])); ?>" onclick="return confirm('Are you sure you want to delete?');">
			  <i class="red ace-icon fa fa-trash bigger-120"> </i>
			</a>
			<?php endif; ?>
		 </li>		
	   </div>
     </div>
<?php endforeach; ?>

 <?php      
    if($this->status == "2"):?>
			<div class="row">
				<div class="col-lg-12"> <br/>
				    <a href="<?php echo $this->url('upload', array('action'=>'upload-form', 'id' => $this->process."-".$this->process_id)); ?>" data-toggle="modal" data-target="#modal">
				       <i class="fa fa-paperclip"></i>&nbsp;&nbsp;Attach Files
				    </a>
				</div>
			</div>
<?php endif;?>

<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>