<?php
/**
 * Layout --- Bottom Navbar
 * chophel@athang.com
 */
?>
<div class="footer">
	<div class="footer-inner">
		<div class="footer-content">
			<span class="bigger-110">
				<span class="blue bolder">Monal-ERP</span>
				&copy; 2014-<?php echo date('Y');?>
			</span>
		</div>
	</div>
</div>

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
	<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
</a>