<?php
/**
 * View -- of Administration/MasterController/addbank
 * chophel@athang.com
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('general', array('action' => 'addbank','id'=>$page)); ?>" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"> <i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">  
				<div class="row">
					<div class="col-lg-12">
						<div  class="form-group">
							<label for="bank" class="control-label">Bank Name En</label>
							<input class="form-control" type="text" name="bank" id="bank" placeholder="Bank Name En" required />
						</div>
						<div  class="form-group">
							<label for="bankDz" class="control-label">Bank Name Dz</label>
							<input class="form-control fs-2" type="text" name="bankDz" id="bankDz" placeholder="Bank Name Dz" required />
						</div>
						<div  class="form-group">
							<label for="bank_code" class="control-label">Bank Abbreviation</label>
							<input class="form-control" type="text" name="bank_code" id="bank_code" placeholder="Bank Code" required />
						</div>
						<div  class="form-group">
							<label for="status" class="control-label">Status</label>
							<div class="radio">
								<label>
									<input class="ace" type="radio" name="status" id="status" value="1" checked />
									<span class="lbl"> Yes </span>
								</label>
								<label>
									<input class="ace" type="radio" name="status" id="status" value="0" />
									<span class="lbl"> No </span>
								</label>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			bank: {
				validators: {
					notEmpty: {
						message: 'Please provide Bank Name En.'
					}
				}
			},
			bankDz: {
				validators: {
					notEmpty: {
						message: 'Please provide Bank Name Dz.'
					}
				}
			},
			bank_code: {
				validators: {
					notEmpty: {
						message: 'Please provide Bank Abbreviation.'
					},
					stringLength: {
						min: 1,
						max: 25,
						message: 'The bank abbreviation must be 1-25 characters.'
					},
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>