<?php
/**
 * View -- of Administration/MasterController/block
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(452,455,458,461,464,468)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-9">
				<form method="POST">
					<div class="row">
						<div class="form-group col-lg-4">
							<label for="district" class="control-label">District</label>
							<select id="district" name="district" class="form-control" data-placeholder="Select">
								<option value="-1" <?php echo ($district_id == '-1')?'selected':'';?>>All</option>
								<?php foreach($this->districtObj->get(array('status'=>'1')) as $district):?>
									<option value="<?php echo $district['id']?>"<?php echo ($district['id']==$district_id)?'selected':'';?>>
										<?php echo $district['district'];?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>
			<div class="col-lg-3 ">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2,$page);?>
				</div>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Block En</th>
					<th>Block Dz</th>
					<th>Code</th>
					<th>District</th>
					<th>Status</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach ($paginator as $row):?>
				<tr>
					<td><?php  echo $i++; ?></td>								       
					<td class="fw-bold"><?php echo $row['block']; ?></td>
					<td class="fs-2 fw-bold"><?php echo $row['blockDz']; ?></td>
					<td><?php echo $row['block_code']; ?></td>
					<td><?php echo $this->districtObj->getColumn($row['district'],'district');?></td>
					<td><?php echo $this->status($row['status']); ?></td>
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
			array('route' => 'general/paginator','action'=>'block','id'=>$this->district_id));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#district').change(function(){
		window.location.href="<?php echo $this->url('general',array('action'=>'block'));?>/"+$(this).val();
	});
	$('#dataTables').DataTable();
});
</script>