<?php
/**
 * View -- of Administration/MasterController/block
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(452,455,458,461,464,468)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-9">
				<form method="POST">
					<div class="row">
						<div class="form-group col-lg-4">
							<label for="country" class="control-label">Country</label>
							<select id="country" name="country" class="form-control" data-placeholder="Select">
								<option value="-1" <?php echo ($country_id == '-1')?'selected':'';?>>All</option>
								<?php foreach($this->countryObj->getAll() as $country):?>
									<option value="<?php echo $country['id']?>"<?php echo ($country['id']==$country_id)?'selected':'';?>>
										<?php echo $country['name'];?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>
			<div class="col-lg-3 ">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2,$page);?>
				</div>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>City</th>
					<th>Country</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach ($paginator as $row):?>
				<tr>
					<td><?php  echo $i++; ?></td>								       
					<td><?php echo $row['city']; ?></td>
					<td><?php echo $this->countryObj->getColumn(array('id'=>$row['country']),'name')?></td>
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
			array('route' => 'general/paginator','action'=>'city','id'=>$this->country_id));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#country').change(function(){
		window.location.href="<?php echo $this->url('general',array('action'=>'city'));?>/"+$(this).val();
	});
	$('#dataTables').DataTable();
});
</script>