<?php 
/**
 * View -- of Administration/MasterController/editvillage
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<?php foreach($villages as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('general', array('action' => 'editvillage','id'=>$page)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"> <i class="ace-icon fa fa-pencil-square-o"></i> <?php echo $this->title; ?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">  
		<div class="panel panel-default">
			<div class="panel-body"> 
				<div class="row">
					<div class="col-lg-12">
						<input type="hidden" id="village_id" name="village_id" value="<?php echo $row['id'];?>" />
						<div class="form-group">  
							<label class="control-label" for="block">Block</label>
							<select id="block" name="block" class="form-control" data-placeholder="Select">
								<option value=""></option>
								<?php foreach($blocks as $block):?>
									<option value="<?php echo $block['id']?>" <?php echo ($row['block']==$block['id'])?'selected':'';?>>
										<?php echo $block['block'];?></option>
								<?php endforeach;?>
							</select>
						</div>
						<div class="form-group"> 
							<label class="control-label" for="village">Village Name En</label>
							<input type="text" class="form-control" value="<?php echo $row['village'];?>" name="village" id="village" placeholder="Village Name En" required /> 
						</div>
						<div class="form-group"> 
							<label class="control-label" for="villageDz">Village Name Dz</label>
							<input type="text" class="form-control" value="<?php echo $row['villageDz'];?>" name="villageDz" id="villageDz" placeholder="Village Name Dz" required /> 
						</div>
						<div  class="form-group">
							<label for="status" class="control-label">Status</label>
							<div class="radio">
								<label>
									<input class="ace" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
									<span class="lbl"> Yes </span>
								</label>
								<label>
									<input class="ace" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
									<span class="lbl"> No </span>
								</label>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			block: {
				validators: {
					notEmpty: {
						message: 'Please select Block.'
					}
				}
			},
			village: {
				validators: {
					notEmpty: {
						message: 'Please provide Village Name En.'
					}
				}
			},
			villageDz: {
				validators: {
					notEmpty: {
						message: 'Please provide Village Name Dz.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>