<?php
/**
 * 
 * View -- of Hr/EmployeeController/indexAction
 * 
 */
$this->headTitle($this->title);
 //$minYear = date('Y', strtotime($minYear)); 
 
?>
<?php echo $this->tabs_helper(array(959,988,990)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
			</div>
		</div>
	</div>
</div>
<div>
	<table class="table table-striped table-hover table-condensed" style="width:100%;" id="dataTables">
		<thead>
			<tr>
				<th>#</th>
				<th>Number</th>
				<th>Date</th>
				<th>Subject</th>
				<th>Status</th>
				<th class='no-sort'>Action</th>
				
			</tr>
		</thead>
		<tbody>
			<?php $i = 1; foreach ($sheet as $rows):?>
				<tr>
					<td><?php echo $i++; ?> </td>
					<td><b><?php echo $rows['number']; ?></b></td>
					<td><?php echo $rows['date']; ?></td>
					<td><?php echo $rows['subject']; ?></td>
					<td><?php echo $this->status($rows['status']); ?></td>
						<td><?php  echo $this->button(6,$rows['process_id'],'','962'); echo $this->button(6,"522-".$rows['process_id'],'','3');?></td>
				</tr>
			<?php 
			endforeach;  
			?>
		</tbody>
	</table>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>

