<?php
/**
 * 
 * View -- of Hr/EmployeeController/addemployeeAction
 * 
 */
    $this->headTitle($this->title);
	
?>
<div class="space-12"></div>
<form id="#form" method="post" action="<?php echo $this->url('notesheet', array('action' => 'addsheet')); ?>" enctype="multipart/form-data">
	<div class="row">
		<div class="col-lg-12"> 
			<div class="widget-box transparent">
				<div class="widget-header widget-header-smaller">
					<h4 class="widget-title blue bolder smaller"> Notesheet </h4>
				</div>
				<div class="widget-body">
					<div class="widget-main padding-24"> 
						<div class="row">  
							<div class="form-group col-lg-3">
								<label>Date:</label>
								<div class="date input-group" id="date" data-date-format="yyyy-mm-dd">
									<input class="form-control" name="date" id="date" type="text" value="<?php echo date('Y-m-d');?>" readonly>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div> 	
							<div class="form-group col-lg-3">
								<label for="priority_type" class="control-label">Priority Type</label>
								<select name="priority_type" id="priority_type" class="form-control" data-placeholder="Select">
									<option value=""> </option>
									<option value="1"> Urgent </option>
									<option value="2"> Not Important </option>
								</select>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-lg-9">
								<label for="subject" class="control-label">Subject</label>
								<input type="text" class="form-control" name="subject" id="subject"  placeholder="Subject">
							</div>
                                <div class="mb-3 col-lg-12">
                                    <textarea type="text" class="form-control" name="description" id="description" placeholder=""></textarea>
                                </div>
                         </div>
						  </div>
					 </div>
				 </div>
			</div>
		</div>
	</div>
	<div class="col-lg-12">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button>    
	</div>
</form>
<script type="text/javascript">	   
$(function(){
	tinymce.init({
    selector: 'textarea',
    height: 200,
    menubar: false,
    
    table_default_styles: {
        width: 'auto', /* Set table width to auto */
        tableLayout: 'auto' /* Ensure table layout is set to auto */
    },
    plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'table'
    ],
    statusbar: false,
    branding: false,
    toolbar: 'undo redo | ' +
    'bold italic backcolor | fontsize | alignleft aligncenter ' +
    'alignright alignjustify | bullist numlist outdent indent | ' +
    'removeformat | link | table',
    fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt',
    content_style: `
        table {
            width: 0 !important; /* Force table width to 0 */
			border-collapse: collapse;
        }
        td {
            width: 0 !important; /* Force table cells width to 0 */
            white-space: nowrap; /* Prevent wrapping */
        }
    `
});
const fv = FormValidation.formValidation(document.getElementById('#form'), {
fields: {
			'priority_type': {
				validators: {
					notEmpty: {
						message: 'Please select Priority Type'
					}
				}
			},
			'subject': {
				validators: {
					notEmpty: {
						message: 'Please Enter Subject'
					}
				}
			},
			'activity': {
				validators: {
					notEmpty: {
						message: 'Please select activity'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
	picker.on('selected', function (e) {
		fv.revalidateField(picker.options.element.name);
	});	
   
});
</script>
