<?php
/**
 * 
 * View -- of Hr/EmployeeController/addemployeeAction
 * 
 */
    $this->headTitle($this->title);
?>
<?php foreach($sheet as $sheets);
//foreach($this->employeeObj->get($sheets['employee']) as $emp);
//$employeeUser = $this->userObj->getColumn(array('employee'=>$emp['id']), 'id');	?>
<div class="space-12"></div>
<form id="#form" method="post" action="<?php echo $this->url('notesheet', array('action' => 'editsheet')); ?>" enctype="multipart/form-data">
	<div class="row">
		<div class="col-lg-12"> 
			<div class="widget-box transparent">
				<div class="widget-header widget-header-smaller">
					<h4 class="widget-title blue bolder smaller"> Notesheet </h4>
				</div>
				<div class="widget-body">
					<div class="widget-main padding-24"> 
						<div class="row">  
							<div class="form-group col-lg-3">
								<label>Date:</label>
								<input  type="hidden" name="id"  value="<?php echo $sheets['id']; ?>" >
								<div class="date input-group" id="date" data-date-format="yyyy-mm-dd">
									<input class="form-control" name="date" id="date" type="text" value="<?php echo $sheets['date']; ?>" readonly>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div> 	
							<div class="form-group col-lg-3">
								<label for="priority_type" class="control-label">Priority Type</label>
							
								<select name="priority_type" id="priority_type" class="form-control" data-placeholder="Select">
								<?php 
										$selected1 =($sheets['priority_type']=='1')? 'selected':'';
										$selected2 =($sheets['priority_type']=='2')? 'selected':'';
									
									?>
									<option value="1" <?php echo $selected1;?> > Urgent</option>
									<option value="2" <?php echo $selected2;?> >Not Important </option>
									
								</select>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-lg-9">
								<label for="subject" class="control-label">Subject</label>
								<input type="text" class="form-control" name="subject" id="subject" value="<?php echo $sheets['subject']?>">
							</div>
                                <div class="mb-3 col-lg-12">
									<textarea type="text" class="form-control" name="description" id="description"><?php echo htmlspecialchars($sheets['description']); ?></textarea>
							</div>
                            </div>
						</div>
					 </div>
				 </div>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button>    
	</div>
	
	
</form>
<script type="text/javascript">	   
$(function(){
	tinymce.init({
		selector: 'textarea',
		height: 200,
		menubar: false,
		plugins: [
			'advlist autolink lists link image charmap print preview anchor',
			'searchreplace visualblocks code fullscreen',
			'insertdatetime media table paste code help wordcount'
		],
		statusbar: false,
		branding: false,
		toolbar: 'undo redo | ' +
		'bold italic backcolor | alignleft aligncenter ' +
		'alignright alignjustify | bullist numlist outdent indent | ' +
		'removeformat | link',
	});
	
	
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
	picker.on('selected', function (e) {
		fv.revalidateField(picker.options.element.name);
	});
   
});
</script>
