<?php
/**
 * 
 * View -- of Hr/EmployeeController/indexAction
 * 
 */
$this->headTitle($this->title);
 $minYear = date('Y', strtotime($minYear)); 
 
?>
<?php echo $this->tabs_helper(array(959,988,990)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
			<form id="#form" method="post" action="<?php echo $this->url('notesheet',array('action' => 'sheet')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form>
			</div>
		</div>
		
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
</div>
<div>
	<table class="table table-striped table-hover table-condensed" style="width:100%;" id="dataTables">
		<thead>
			<tr>
				<th>#</th>
				<th>Number</th>
				<th>Date</th>
				<th>Subject</th>
				<th>Status</th>
				<?php if($this->button(1)!=""):?>
				<th class='no-sort'>Action</th>
				<?php endif;?>
			</tr>
		</thead>
		<tbody>
			<?php $i = 1; foreach ($sheet as $rows):?>
				<tr>
					<td><?php echo $i++; ?> </td>
					<td><b><?php echo $rows['number']; ?></b></td>
					<td><?php echo $rows['date']; ?></td>
					<td><?php echo $rows['subject']; ?></td>
					<td><?php echo $this->status($rows['status']); ?></td>
				<?php if($this->button(1)!=""):?>
						<td><?php  echo $this->button(6,$rows['id'],'','962'); echo $this->button(6,"522-".$rows['id'],'','3');?></td>
					<?php endif;?>
				</tr>
			<?php 
			endforeach;  
			?>
		</tbody>
	</table>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>

