<?php
/**
 * 
 * View -- of Hr/LeaveController/encashmentAction
 * 
 */
$this->headTitle($this->title); ?>

<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
			
			<table class="table card-table text-nowrap" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Date</th>
						<th>Purpose</th>
						<th>Status</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php
					  $i = 1; 
					  foreach ($sittingObj->getAll() as $row):?>
						<tr>
							<td><?php echo $i; ?>. </td>
							<td><?php echo $row['date']; ?></td>							
							<td><?php echo $row['purpose']; ?></td>							
							<td><?php echo $this->status($row['status']); ?></td>
							<td><?php echo $this->button(1,$row['id']);?></td>
						</tr>
					<?php 
					$i++;
					endforeach;  
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});

	$('#dataTables').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>


