<?php 
/**
 * chophel@athang.com -- 2022
 * View -- of Acl/ButtonController/aclAction
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(232,234,236,238)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-6">
				<form method="POST" class="form-horizontal">
					<div class="form-group row">
						<label class="control-label col-sm-4">Module</label>
						<div class="col-sm-8">
							<select id="module" name="module" class="form-control" data-placeholder="Select">
								<?php foreach($this->modules as $module):?>
								<?php $selected = ($module['id']==$this->resource)?'selected':'';?>
									<option value="<?php echo $module['id']?>"<?php echo $selected;?>><?php echo $module['module'];?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-wrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Menu/*Sub-Menu/**Item</th>
					<th>Resource/Privilege</th>	
					<th>Acl Role</th>
					<th>Process</th>
					<th>Process Action</th>
					<th>Permission Level</th>
					<th>Dashboard</th>
					<th>System</th>
					<?php if($this->button(1)!=""):?>
					<th class='no-sort'>Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach ($paginator as $acl):?>
				<tr>
					<td><?php  echo $i++; ?></td>	       
					<td><?php if (strlen($acl['tabindex']) == 1 ): ?>
						<?php echo $acl['menu']; ?>
					<?php elseif (strlen($acl['tabindex']) == 2):?>	
						<?php echo "<b class='blue bigger-120'>*</b>".$acl['menu']; ?>
					<?php else: ?>	
						<?php echo "<b class='blue bigger-120'>*</b><b class='red bigger-120'>*</b>".$acl['menu']; ?>							
					<?php endif; ?></td>
					<td><?php echo $acl['controller']."/".$acl['action']; ?></td>
					<td><?php echo $this->roleObj->getColumn($acl['role'],'role'); ?></td>
					<td><strong><?php echo ($acl['process']!='0')?$this->processObj->getColumn($acl['process'],'process'):'-';?></strong></td>
					<td><strong><?php echo ($acl['process_action']!='0')?$this->pactionObj->getColumn($acl['process_action'],'action'):'-'; ?></strong></td>
					<td class="text-center"><?php echo ($acl['permission_level']!='0')?"<span class='label label-".$this->statusObj->getColumn($acl['permission_level'],'label')." label-white'>".$this->statusObj->getColumn($acl['permission_level'],'status')."</span>":"<span class='label label-grey label-white'>All Levels</span>"; ?></td>
					<td class="text-center"><?php echo ($acl['dashboard']=='1')?"<span class='ace-icon fa fa-check fa-lg green'></span>":"<span class='ace-icon fa fa-times fa-lg red'></span>"; ?></td>
					<td class="text-center"><?php echo ($acl['system']=='1')?"<span class='ace-icon fa fa-check fa-lg green'></span>":"<span class='ace-icon fa fa-times fa-lg red'></span>"; ?></td>
					<?php if($this->button(1)!=""):?>
					<td><?php echo $this->button(1, $acl['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','acl_pagination.phtml', 
			array('route' => 'button/paginator','action'=>'acl','id'=>$this->resource,'role'=>'0','task'=>'0'));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#module').change(function(){
		window.location.href="<?php echo $this->url('button',array('action'=>'acl'));?>/"+$(this).val();
	});
	$('#dataTables').DataTable();
});
</script>