<?php 
/**
 * chophel@athang.com 
 * View -- of Acl/ButtonController/buttonAction
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(232,234,236,238)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-6">
				<form method="POST" class="form-horizontal">
					<div class="form-group row">
						<label class="control-label col-sm-4">Module</label>
						<div class="col-sm-8">
							<select id="module" name="module" class="form-control" data-placeholder="Select">
								<?php foreach($this->modules as $module):?>
								<?php $selected = ($module['id']==$this->resource)?'selected':'';?>
									<option value="<?php echo $module['id']?>"<?php echo $selected;?>><?php echo $module['module'];?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-wrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Menu (Resource/Action)</th>
					<th>Container Page</th>
					<th>is Button</th>		
					<th>Button Type</th>
					<th>Button Position</th>
					<th>Icon</th>
					<th>Label</th>
					<th>Class</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach($paginator as $acl):?>
				<tr>
					<td><?php  echo $i++; ?></td>								       
					<td><strong><?php echo $acl['menu']; ?></strong> (<?php echo $acl['controller']."/".$acl['action']; ?>)</td>
					<td><?php echo ($acl['parent_page'] == '0')? '' : $this->aclObj->getColumn($acl['parent_page'], 'menu');?></td>
					<td class="text-center"><?php echo ($acl['btn']=='1')?"<span class='ace-icon fa fa-check fa-lg green'></span>":"<span class='ace-icon fa fa-times fa-lg red'></span>"; ?></td>
					<td>
						<?php if($acl['btn_type']==1):
								echo"Normal";
							elseif($acl['btn_type']==2):
								echo"Modal";
							endif;
						?>
					</td>
					<td><?php echo ($acl['button_position'] == '0')? '' : $this->btnpositionObj->getColumn($acl['button_position'], 'button_position');?></td>
					<td class="text-center"><?php echo ($acl['btn']=='1')?"<i class='ace-icon ".$acl['icon']." fa-lg'></i>":""; ?></td>
					<td><?php echo ($acl['btn_label'] == '0')?'':$acl['btn_label'];?></td>
					<td><?php echo ($acl['class'] == '0')?'':$acl['class'];?></td>
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $acl['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','acl_pagination.phtml', 
			array('route' => 'button/paginator','action'=>'button','id'=>$this->resource,'role'=>'0','task'=>'0'));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#module').change(function(){
		window.location.href="<?php echo $this->url('button',array('action'=>'button'));?>/"+$(this).val();
	});
	$('#dataTables').DataTable();
});
</script>