<?php 
/**
 * chophel@athang.com 
 * View -- of Acl/ButtonController/menuAction
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(232,234,236,238)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-6">
				<form method="POST" class="form-horizontal">
					<div class="form-group row">
						<label class="control-label col-sm-4">Module</label>
						<div class="col-sm-8">
							<select id="module" name="module" class="form-control" data-placeholder="Select">
								<?php foreach($this->modules as $module):?>
								<?php $selected = ($module['id']==$this->resource)?'selected':'';?>
									<option value="<?php echo $module['id']?>"<?php echo $selected;?>><?php echo $module['module'];?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Main Menu</th>
					<th>Second Level Menu</th>
					<th>Third Level Menu</th>
					<th>Display Menu</th>	
					<th>Menu Icon</th>	
					<th>Description</th>
					<?php if($this->button(1)!=""):?>
					<th class='no-sort'>Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach ($paginator as $acl):?>
				<tr>
					<td><?php  echo $i++; ?></td>								       
					<?php if (strlen($acl['tabindex']) == 1 ): ?>
						<td><?php echo $acl['menu']; ?></td>
						<td></td>
						<td></td>
					<?php elseif (strlen($acl['tabindex']) == 2):?>	
						<td></td>
						<td><?php echo $acl['menu']; ?></td>		
						<td></td>				
					<?php else: ?>							
						<td></td>
						<td></td>
						<td><?php echo $acl['menu']; ?></td>	
					<?php endif; ?>
					<td class="text-center"><?php echo ($acl['display']=='1')?"<span class='ace-icon fa fa-check fa-lg green'></span>":"<span class='ace-icon fa fa-times fa-lg red'></span>"; ?></td>
					<td class="text-center"><?php echo ($acl['btn']!=1)?"<i class='ace-icon ".$acl['icon']." fa-lg'></i>":""; ?></td>
					<td><?php echo $acl['description']; ?></td>
					<?php if($this->button(1)!=""):?>
					<td><?php echo $this->button(1, $acl['id'].'_'.$page);?></td>
					<?php endif;?>	
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','acl_pagination.phtml', 
			array('route' => 'button/paginator','action'=>'menu','id'=>$this->resource,'role'=>'0','task'=>'0'));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#module').change(function(){
		window.location.href="<?php echo $this->url('button',array('action'=>'menu'));?>/"+$(this).val();
	});
	$('#dataTables').DataTable();
});
</script>