<?php
/**
 * View -- 500 Error
 * chophel@athang.com
 */
?>
<div class="error-container">
    <div class="well">
        <h1 class="grey lighter smaller">
            <span class="blue bigger-125">
                <i class="ace-icon fa fa-random"></i>
                500
            </span>
            <?= $this->message ?>
        </h1>

        <hr />
        <h3 class="lighter smaller">
            But we are working
            <i class="ace-icon fa fa-wrench icon-animated-wrench bigger-125"></i>
            on it!
        </h3>

        <?php if (! empty($this->display_exceptions)) : ?>
            <?php if (isset($this->exception) && $this->exception instanceof \Throwable) : ?>
        
        <h2>Additional information:</h2>
        <h3><?= get_class($this->exception) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre style="background-color:#fff"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre style="background-color:#fff"><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre style="background-color:#fff"><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
            </dd>
        </dl>

                <?php if ($ex = $this->exception->getPrevious()) : ?>
        <hr/>

        <h2>Previous exceptions:</h2>
        <ul class="list-unstyled">
                    <?php $icount = 0 ?>
                    <?php while ($ex) : ?>
            <li>
                <h3><?= get_class($ex) ?></h3>
                <dl>
                    <dt>File:</dt>
                    <dd>
                        <pre style="background-color:#fff"><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
                    </dd>
                    <dt>Message:</dt>
                    <dd>
                        <pre style="background-color:#fff"><?= $this->escapeHtml($ex->getMessage()) ?></pre>
                    </dd>
                    <dt>Stack trace:</dt>
                    <dd>
                        <pre style="background-color:#fff"><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
                    </dd>
                </dl>
            </li>
                        <?php
                        $ex = $ex->getPrevious();
                        if (++$icount >= 50) {
                            echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
                            break;
                        }
                        ?>
                    <?php endwhile ?>
        </ul>
                <?php endif ?>
            <?php else : ?>
                <h3>No Exception available</h3>
            <?php endif ?>
        <?php endif ?>

        <hr />
        <div class="center">
            <a href="javascript:history.back()" class="btn btn-grey">
                <i class="ace-icon fa fa-arrow-left"></i>
                Go Back
            </a>
            <a href="<?php echo $this->url('home'); ?>" class="btn btn-primary">
                <i class="ace-icon fa fa-tachometer"></i>
                Dashboard
            </a>
        </div>
    </div>
</div>