<?php
/**
 *  pay head report---Hr/ReportController/savingAction  
 */
	$this->headTitle($this->title);
?>
<?php //echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'cashreport')); ?>
<?php echo $this->tabs_helper(array(922,924,925,930,931,932,923)); ?>
<?php
	//extract($this->data);
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Cash Report
		</h4>
	</div>	
	<div class="widget-body">
		<div class="widget-main">
		<form method="post" action="<?php echo $this->url('preport', array('action' => 'cashreport')); ?>" >
				<div class="row">
					<div class="form-group col-lg-2">
						<label for="year" class="control-label">Year</label>
						<select id="year" name="year" class="form-control" data-placeholder="Select">
							<?php 
							for($year=date('Y');$year >= $minYear;$year--):
							?>
								<?php $selected = ($year == $data['year'])?"selected":"";?>
								<option value="<?php echo $year;?>" <?php echo $selected;?>>
									<?php echo $year;?> 
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="month" class="control-label">Month</label>
						<select id="month" name="month" class="form-control" data-placeholder="Select">
							<?php for($month=1; $month<13; $month++):?>
								<?php $selected = ($month == $data['month'])?'selected':'';?>
								<option value="<?php echo $month;?>" <?php echo $selected; ?>>
									<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
								</option> 
							<?php endfor;?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data['region'])?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $location):
							?>
								<?php $selected = ($location['id'] == $data['location'])?'selected':'';?>
								<option value="<?php echo $location['id'];?>" <?php echo $selected;?>>
									<?php echo $location['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<div class="space-10"></div>
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="submit" class="btn btn-sm btn-success"><i class="fa fa-refresh"></i> refresh </button>
					</div>
				</div>
			</form>
			<div class="row"><div class="space-12"></div></div>
			<div class="row">
			<?php $month = $data['month'];$year = $data['year'];?>
				<div class="col-lg-12">
				    <input type="hidden" name="c_date" id="c_date" value="<?php echo date("F", strtotime(date("d-$month-y"))).','.$data['year'];?>" />
					<strong> For the Month of : <?php echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $year; ?>
					<?php
						if($data['location'] > 0):
							$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data['location']));
						elseif($data['region'] > 0):
							$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data['region']));
						else:
							$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year));
						endif;
						if(sizeof($payrolls) > 0):
							//Payroll Generated
						else:
							if($data['location'] > 0):
								$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data['location']));
							elseif($data['region'] > 0):
								$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data['region']));
							else:
								$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year));
							endif;
							if(sizeof($temp_payrolls) > 0)://Draft?>
								<span class="label label-danger">DRAFT</span>
					<?php	else: //Not Generated ?>
								<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
					<?php	endif;
						endif;
					?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<div class="space-6"></div>
			<table class="table table-condensed table-bordered" id="example">
				<thead>
					<tr>
						<th>#</th>
						<th>NAME</th>
						<th>DESIGNATION</th>
						<th>GRADE</th>
						<th>NET AMOUNT</th>
						<th>PLACE</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					$i =1;
					$total_netpay = 0;
					if($data['location'] > 0):
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data['location']));
					elseif($data['region'] > 0):
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data['region']));
					else:
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year));
					endif;
					if(sizeof($payrolls) > 0):
					foreach($payrolls as $payroll):
						$bank_account_no = $this->employeeObj->getColumn($payroll['employee'],'bank_account_no');
						//if($bank_account_no == 0 || $bank_account_no == ''):
					?>
						<tr>
							<td><?php echo $i++;?></td>
							<td><?php echo $payroll['full_name'];?> </td>
							<td><?php echo $payroll['position_title'];?></td>
							<td><?php echo $payroll['code'];?></td>
							<td> <?php $total_netpay += $payroll['net_pay']; echo $this->decimal($payroll['net_pay']);?></td>
							<td><?php echo $payroll['location'];?></td>
						</tr>
			  <?php 	//endif;
					endforeach; 
					else:
						if($data['location'] > 0):
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data['location']));
						elseif($data['region'] > 0):
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data['region']));
						else:
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year));
						endif;
						if(sizeof($temp_payrolls) > 0):
							foreach($temp_payrolls as $temp_payroll):
								$bank_account_no = $this->employeeObj->getColumn($temp_payroll['employee'],'bank_account_no');
								//if($bank_account_no == 0 || $bank_account_no == ''):
					?>
							<tr>
								<td><?php echo $i++;?></td>
								<td><?php echo $temp_payroll['full_name'];?> </td>
								<td><?php echo $temp_payroll['position_title'];?></td>
								<td><?php echo $temp_payroll['code'];?></td>
								<td><?php $total_netpay += $temp_payroll['net_pay']; echo $this->decimal($temp_payroll['net_pay']);?></td>
								<td><?php echo $temp_payroll['location'];?></td>
							</tr>
					<?php   	//endif;
							endforeach;
						endif;
					endif;?>							
				</tbody>
				<tfoot>
				    <tr>
						<td></td>
						<td></td>
						<td></td>
						<td><strong>Total:  </strong></td>
						<td><b><?php echo $total_netpay;?></b></td>
						<td></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
	var title_table = 'Cash Report for the Month : '+$('#c_date').val();
	$('#example').DataTable( {
		dom: 'Bfrtip',
		/*buttons: [
			'copy', 'csv', 'excel', 'pdf', 'print'
		]*/
		lengthMenu: [
			[ 25, 50, -1 ],
			[ '25 rows', '50 rows', 'Show all' ]
		],
		columnDefs: [ {
			visible: false
		} ],
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-files-o"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-file-excel-o"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="fa fa-file-pdf-o"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-print"></i> Print',
				titleAttr: 'Print'
			},
			'pageLength','colvis'
		],
		select:true
	} );
	$('select#region').on('change',function(){
			$.post(
				"<?php echo $this->url('employee', array('action' => 'getlocation'));?>",
				{
					regionId: $(this).val(),
				},
				function(data){
					$('select#location').html(data.location);
					$('select#location').trigger('chosen:updated');
				},
				'json'
			);
		});
	$('form select').chosen({ allow_single_deselect: true });
</script>
