<?php
/**
 * Control Summary
 * Report -- of Payroll
 */
	$this->headTitle($this->title);
?>
<?php //echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'controlsummary')); ?>
<?php echo $this->tabs_helper(array(922,924,925,930,931,932,923)); ?>
<?php	
	$earning= ceil(count($earningHead)/2); //no of earning columns
	$deduction = ceil(count($deductionHead)/2); //no of deduction columns
	$regions = $this->regionObj->getAll();
	$locations = $this->locationObj->select(array('region'=>$data['region']));
	$activities = $this->activityObj->getAll();
$minYear = ($this->minYear > 0)?$this->minYear:date('Y');
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Control Summary
		</h4>
		<div class="widget-toolbar hidden-xs">
			<a style='cursor:pointer' id="print">
				<i class="ace-icon fa fa-file-pdf-o red"></i>
			</a>
		</div>
	</div>
	<div class="widget-body">
		<div class="widget-main">
		<form method="post" action="<?php echo $this->url('preport', array('action' => 'controlsummary')); ?>" >
				<div class="row">
					<div class="form-group col-lg-2">
						<label for="year" class="control-label">Year</label>
						<select id="year" name="year" class="form-control" data-placeholder="Select">
							<?php 
							for($year=date('Y');$year >= $minYear;$year--):
							?>
								<?php $selected = ($year == $data['year'])?"selected":"";?>
								<option value="<?php echo $year;?>" <?php echo $selected;?>>
									<?php echo $year;?> 
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="month" class="control-label">Month</label>
						<select id="month" name="month" class="form-control" data-placeholder="Select">
							<?php for($month=1; $month<13; $month++):?>
								<?php $selected = ($month == $data['month'])?'selected':'';?>
								<option value="<?php echo $month;?>" <?php echo $selected; ?>>
									<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
								</option> 
							<?php endfor;?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data['region'])?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>        
					<div class="form-group col-lg-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($locations as $location):
							?>
								<?php $selected = ($location['id'] == $data['location'])?'selected':'';?>
								<option value="<?php echo $location['id'];?>" <?php echo $selected;?>>
									<?php echo $location['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="activity" class="control-label">Activity</label>
						<select class="form-control" id="activity" name="activity" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach($activities as $activity):
							?>
								<?php $selected = ($activity['id'] == $data['activity'])?'selected':'';?>
								<option value="<?php echo $activity['id'];?>" <?php echo $selected;?>>
									<?php echo $activity['activity'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div> 
					<div class="form-group col-lg-1">
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="submit" class="btn btn-sm btn-info"><i class="fa fa-refresh"></i> refresh</button>
					</div>
				</div>
			</form>
		<?php if($data['region'] !='' && $data['location'] != '' && $data['activity'] != ''):?>
			<div class="row">
				<div class="col-lg-12">
					<?php $month = $data['month'];?>
					<input type="hidden" name="cs_date" id="cs_date" value="<?php echo date("F", strtotime(date("d-$month-y"))).','.$data['year'];?>" />
					<strong>
						<h3>Control Summary for the Month of : <?php echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $data['year']; ?>
						<?php
							$loc_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
							);
							if($data['region'] > 0):
								$loc_data['r.id'] = $data['region']; 
							endif;
							if($data['location'] > 0):
								$loc_data['his.location'] = $data['location']; 
							endif;
							$locations = $this->payrollObj->controlsummaryLocation($loc_data);
							if(sizeof($locations) > 0):
								//generated
							else: //temp payroll
								$temp_locations = $this->temppayrollObj->controlsummaryLocation($loc_data);
								if(sizeof($temp_locations) > 0):
						?>
								<span class="label label-danger">DRAFT</span>
						<?php   else: //not prepared?>
								<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
						<?php   endif;
							endif;?>
						</h3>
						<label><i class="blue fa fa-globe"></i> Region: </label> <span><?php echo $region = ($data["region"] == -1)? "All": $this->regionObj->getColumn($data["region"], 'region');?></span>
						<label><i class="orange fa fa-map-marker"></i> Location: </label> <span><?php echo $loc = ($data["location"] == -1)? "All": $this->locationObj->getColumn($data["location"], 'location');?></span>
						<label><i class="blue fa fa-sitemap"></i> Activity: </label> <span><?php echo $act = ($data["activity"] == -1)? "All": $this->activityObj->getColumn($data["activity"], 'activity');?></span>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<table class="table table-condensed table-bordered" id="example">
				<thead>
					<tr>
						<th  rowspan="2">Location</th>
						<th  rowspan="2">Section/<br>Division</th>
						<th  rowspan="2">Total Entries</th>
						<th  colspan="<?php echo $earning;?>" style="text-align:center">Earnings</th>
						<th  colspan="<?php echo $deduction;?>" style="text-align:center">Deductions</th>
						<th  rowspan="2">LWPD</th>
						<th  rowspan="2">Tot Ded/<br>Net Pay</th>
					</tr>
					<tr>
						<!-- Earnings columns -->
						<?php foreach ($this->earningHead as $key => $row):?>
							<?php if($key%2==0):?><th><?php endif; ?>
							<?php echo $row['code'];?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></th><?php endif; ?>
						<?php endforeach;?> 
						
						<!-- Deduction columns -->
						<?php foreach ($this->deductionHead as $key => $row):?>
							<?php if($key%2==0):?><th><?php endif; ?>
							<?php echo $row['code'];?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></th><?php endif; ?>
						<?php endforeach;?>
					</tr>
				</thead>
				<tbody>							
				<?php
					$loc_data = array(
							'year' => $data['year'],
							'month' => $data['month'],
					);
					if($data['region'] > 0):
						$loc_data['r.id'] = $data['region']; 
					endif;
					if($data['location'] > 0):
						$loc_data['his.location'] = $data['location']; 
					endif;
					$grand_tot_entries = 0;
					$grand_earning = array();
					$grand_deduction = array();
					$grand_tot_ded = 0;
					$grand_net_pay = 0;
					$grand_lwpd = 0;
					$locations = $this->payrollObj->controlsummaryLocation($loc_data);
					if(sizeof($locations) > 0):
					foreach($locations as $location):
						$loc_tot_entries = 0;
						$loc_tot_dlwp = 0;
						$tot_earning = array();
						$tot_deduction = array();
						$tot_tot_ded = 0;
						$tot_net_pay = 0;
						$act_data = array(
							'year' => $data['year'],
							'month' => $data['month'],
							'his.location' => $location['location_id']
						);
						if($data['activity'] > 0):
							$act_data['his.activity'] = $data['activity']; 
						endif;
						$activities = $this->payrollObj->controlsummaryActivity($act_data);
						foreach($activities as $activity):
						$r_total_entries = $this->payrollObj->getTotalEntries(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R');
						$o_total_entries = $this->payrollObj->getTotalEntries(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O');
						$total_entries = $r_total_entries + $o_total_entries;
						$loc_tot_entries += $total_entries;
						$grand_tot_entries += $total_entries;
						
						$r_dlwp = $this->payrollObj->getLWPD(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R');
						$o_dlwp = $this->payrollObj->getLWPD(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O');
						$total_dlwp = $r_dlwp + $o_dlwp;
						$loc_tot_dlwp += $total_dlwp;
						$grand_lwpd += $total_dlwp;
				?>
				<?php if($r_total_entries > 0):?>
					<tr style="text-align:right;">
						<td style="border-top: 1px solid #5add55;"><?php echo $location['location'];?></td>
						<td style="border-top: 1px solid #5add55;"><?php echo $activity['activity'];?>(R)</td>
						<td style="border-top: 1px solid #5add55;"><?php echo $r_total_entries;?></td>
						<!-- values for earning column -->
						<?php foreach ($this->earningHead as $key => $row):
							$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="text-align:right; border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paydetailObj->getControlSummaryAmt($payhead_data,'R');
								echo $this->decimal($amount);
								//$tot_earning[$key] += $amount;
								//$grand_earning[$key] += $amount;
							?>											
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						<!-- values for deduction column -->
						<?php foreach ($this->deductionHead as $key => $row):
								$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="text-align:right;border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paydetailObj->getControlSummaryAmt($payhead_data,'R');
								echo $this->decimal($amount);
								//$tot_deduction[$key] += $amount;
								//$grand_deduction[$key] += $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>	
						<td  style="border-top: 1px solid #5add55;">
							<?php echo $this->decimal($r_dlwp);?>
						</td>
						<td style="border-top: 1px solid #5add55;">
							<?php $r_tot_ded = $this->payrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R','total_deduction');
								$tot_tot_ded += $r_tot_ded; $grand_tot_ded += $r_tot_ded;
								echo $this->decimal($r_tot_ded);?><br>
							<?php $r_net_pay = $this->payrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R','net_pay');
								$tot_net_pay += $r_net_pay; $grand_net_pay += $r_net_pay;
								echo $this->decimal($r_net_pay);?>
						</td>
					</tr>
				<?php endif;
				if($o_total_entries > 0):
				?>
					<tr style="text-align:right;">
						<td style="border-top: 1px solid #5add55;" ><?php echo $location['location'];?></td>
						<td style="border-top: 1px solid #5add55;" ><?php echo $activity['activity'];?>(O)</td>
						<td style="border-top: 1px solid #5add55;"><?php echo $o_total_entries;?></td>
						<!-- values for earning column -->
						<?php foreach ($this->earningHead as $key => $row):
							$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paydetailObj->getControlSummaryAmt($payhead_data,'O');
								echo $this->decimal($amount);
								//$tot_earning[$key] += $amount;
								//$grand_earning[$key] += $amount;
							?>											
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						<!-- values for deduction column -->
						<?php foreach ($this->deductionHead as $key => $row):
								$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paydetailObj->getControlSummaryAmt($payhead_data,'O');
								echo $this->decimal($amount);
								//$tot_deduction[$key] += $amount;
								//$grand_deduction[$key] += $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>	
						<td  style="border-top: 1px solid #5add55;">
							<?php echo $this->decimal($o_dlwp);?>
						</td>
						<td style="border-top: 1px solid #5add55;">
							<?php $o_tot_ded = $this->payrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O','total_deduction');
								$tot_tot_ded += $o_tot_ded; $grand_tot_ded += $o_tot_ded;
								echo $this->decimal($o_tot_ded);?><br>
							<?php $o_net_pay = $this->payrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O','net_pay');
								$tot_net_pay += $o_net_pay; $grand_net_pay += $o_net_pay;
								echo $this->decimal($o_net_pay);?>
						</td>
					</tr>
				<?php endif;?>
				<?php 	endforeach;?>
					<tr style="text-align:right;">
						<td style="border-top: 1px solid #5add55;"></td>
						<td style="border-top: 1px solid #5add55;">Total</td>
						<td style="border-top: 1px solid #5add55;"><?php echo $loc_tot_entries;?></td>
						<!-- values for earning column -->
						<?php foreach ($this->earningHead as $key => $row):?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
								<?php //echo $this->decimal($tot_earning[$key]); ?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						  
						<!-- values for deduction column -->
						<?php foreach ($this->deductionHead as $key => $row):?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
								<?php //echo $this->decimal($tot_deduction[$key]); ?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						<td style="border-top: 1px solid #5add55;" >
							<?php echo $this->decimal($loc_tot_dlwp);?>
						</td>
						<td style="border-top: 1px solid #5add55;">
							<?php echo $this->decimal($tot_tot_ded);?><br>
							<?php echo $this->decimal($tot_net_pay);?>
						</td>
					</tr>
				<?php endforeach;
				else: //from temp payroll
					$temp_locations = $this->temppayrollObj->controlsummaryLocation($loc_data);
					//echo "<pre>";print_r($temp_locations);
					foreach($temp_locations as $location):
						$loc_tot_entries = 0;
						$loc_tot_dlwp = 0;
						$tot_earning = array();
						$tot_deduction = array();
						$tot_tot_ded = 0;
						$tot_net_pay = 0;
						$act_data = array(
							'year' => $data['year'],
							'month' => $data['month'],
							'his.location' => $location['location_id']
						);
						if($data['activity'] > 0):
							$act_data['his.activity'] = $data['activity']; 
						endif;
						$activities = $this->temppayrollObj->controlsummaryActivity($act_data);
						foreach($activities as $activity):
						$r_total_entries = $this->temppayrollObj->getTotalEntries(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R');
						$o_total_entries = $this->temppayrollObj->getTotalEntries(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O');
						$total_entries = $r_total_entries + $o_total_entries;
						$loc_tot_entries += $total_entries;
						$grand_tot_entries += $total_entries;
						$r_dlwp = $this->temppayrollObj->getLWPD(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R');
						$o_dlwp = $this->temppayrollObj->getLWPD(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O');
						$total_dlwp = $r_dlwp + $o_dlwp;
						$loc_tot_dlwp += $total_dlwp;
						$grand_lwpd += $total_dlwp;
				?>
				<?php if($r_total_entries > 0):?>
					<tr style="text-align:right;">
						<td style="border-top: 1px solid #5add55;" ><?php echo $location['location'];?></td>
						<td style="border-top: 1px solid #5add55;" ><?php echo $activity['activity'];?>(R)</td>
						<td style="border-top: 1px solid #5add55;"><?php echo $r_total_entries;?></td>
						<!-- values for earning column -->
						<?php foreach ($this->earningHead as $key => $row):
							$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paystructureObj->getControlSummaryAmt($payhead_data,'R');
								echo $this->decimal($amount);
								$tot_earning[$key] = $amount;
								$grand_earning[$key] = $amount;
							?>											
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						<!-- values for deduction column -->
						<?php foreach ($this->deductionHead as $key => $row):
								$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paystructureObj->getControlSummaryAmt($payhead_data,'R');
								echo $this->decimal($amount);
								$tot_deduction[$key] = $amount;
								$grand_deduction[$key] = $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>	
						<td  style="border-top: 1px solid #5add55;">
							<?php echo $this->decimal($r_dlwp);?>
						</td>
						<td  style="border-top: 1px solid #5add55;">
							<?php $r_tot_ded = $this->temppayrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R','total_deduction');
								$tot_tot_ded += $r_tot_ded; $grand_tot_ded += $r_tot_ded;
								echo $this->decimal($r_tot_ded);?><br>
							<?php $r_net_pay = $this->temppayrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'R','net_pay');
								$tot_net_pay += $r_net_pay; $grand_net_pay += $r_net_pay;
								echo $this->decimal($r_net_pay);?>
						</td>
					</tr>
				<?php endif;
				if($o_total_entries > 0):
				?>
					<tr style="text-align:right;">
						<td style="border-top: 1px solid #5add55;"><?php echo $location['location'];?></td>
						<td style="border-top: 1px solid #5add55;"><?php echo $activity['activity'];?>(O)</td>
						<td style="border-top: 1px solid #5add55;" ><?php echo $o_total_entries;?></td>
						<!-- values for earning column -->
						<?php foreach ($this->earningHead as $key => $row):
							$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paystructureObj->getControlSummaryAmt($payhead_data,'O');
								echo $this->decimal($amount);
								$tot_earning[$key] = $amount;
								$grand_earning[$key] = $amount;
							?>											
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						<!-- values for deduction column -->
						<?php foreach ($this->deductionHead as $key => $row):
								$payhead_data = array(
								'year' => $data['year'],
								'month' => $data['month'],
								'pd.pay_head' => $row['id'],
								'his.location' => $location['location_id'],
								'his.activity' => $activity['activity_id'],
							);
						?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; ?>
							<?php
								$amount = $this->paystructureObj->getControlSummaryAmt($payhead_data,'O');
								echo $this->decimal($amount);
								$tot_deduction[$key] = $amount;
								$grand_deduction[$key] = $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>	
						<td  style="border-top: 1px solid #5add55;">
							<?php echo $this->decimal($o_dlwp);?>
						</td>
						<td style="border-top: 1px solid #5add55;">
							<?php $o_tot_ded = $this->temppayrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O','total_deduction');
								$tot_tot_ded += $o_tot_ded; $grand_tot_ded += $o_tot_ded;
								echo $this->decimal($o_tot_ded);?><br>
							<?php $o_net_pay = $this->temppayrollObj->getControlSummarySum(array('year' => $data['year'],'month' => $data['month'],'his.location' => $location['location_id'],'his.activity' => $activity['activity_id']),'O','net_pay');
								$tot_net_pay += $o_net_pay; $grand_net_pay += $o_net_pay;
								echo $this->decimal($o_net_pay);?>
						</td>
					</tr>
				<?php endif;?>
				<?php 	endforeach;?>
					<tr style="text-align:right;">
						<td style="border-top: 1px solid #5add55;"></td>
						<td style="border-top: 1px solid #5add55;">Total</td>
						<td style="border-top: 1px solid #5add55;"><?php echo $loc_tot_entries;?></td>
						<!-- values for earning column -->
						<?php foreach ($this->earningHead as $key => $row):?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif;if(!empty($tot_earning[$key])):echo $this->decimal($tot_earning[$key]);endif; ?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						  
						<!-- values for deduction column -->
						<?php foreach ($this->deductionHead as $key => $row):?>
							<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif; if(!empty($tot_deduction[$key])):echo $this->decimal($tot_deduction[$key]);endif;?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						<td style="border-top: 1px solid #5add55;" >
							<?php echo $this->decimal($loc_tot_dlwp);?>
						</td>
						<td style="border-top: 1px solid #5add55;" >
							<?php echo $this->decimal($tot_tot_ded);?><br>
							<?php echo $this->decimal($tot_net_pay);?>
						</td>
					</tr>
				<?php endforeach;
				endif; ?>
				<tr style="text-align:right;">
					<td style="border-top: 1px solid #5add55;"></td>
					<td style="border-top: 1px solid #5add55;"><strong>GRAND TOTAL</strong></td>
					<td style="border-top: 1px solid #5add55;"><?php echo $grand_tot_entries;?></td>
					<!-- values for earning column -->
					<?php foreach ($this->earningHead as $key => $row):?>
						<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif;if(!empty($grand_earning[$key])):?><strong><?php echo $this->decimal($grand_earning[$key]); ?></strong><?php endif;?>	 
						<?php if($key%2==0):?><br><?php endif; ?>
						<?php if($key%2!=0):?></td><?php endif; ?> 
					<?php endforeach;?>
					  
					<!-- values for deduction column -->
					<?php foreach ($this->deductionHead as $key => $row):?>
						<?php if($key%2==0):?><td style="border-top: 1px solid #5add55;"><?php endif;if(!empty($grand_earning[$key])): ?><strong><?php echo $this->decimal($grand_deduction[$key]); ?>	</strong><?php endif;?>
						<?php if($key%2==0):?><br><?php endif; ?>
						<?php if($key%2!=0):?></td><?php endif; ?> 
					<?php endforeach;?>
					<td style="border-top: 1px solid #5add55;" >
						<?php echo $this->decimal($grand_lwpd);?>
					</td>
					<td style="border-top: 1px solid #5add55;">
						<strong><?php echo $this->decimal($grand_tot_ded);?><br>
						<?php echo $this->decimal($grand_net_pay);?></strong>
					</td>
				</tr>
				</tbody>
			</table>
		<?php 
			else:
			?>
			<div class="alert alert-success fade in">  
				<strong>Click the Refresh button after selecting required region, location and activity</strong>
			 </div>	
			<?php 
			endif;?>
		</div>
	</div>
</div>
	
<script>
	var title_table = 'Control Summary for the Month : '+$('#cs_date').val();
	$('#example').DataTable( {
		scrollX:        true,
		ordering: false,
		dom: 'Bfrtip',
		/*buttons: [
			'copy', 'csv', 'excel', 'pdf', 'print'
		]*/
		lengthMenu: [
			[ 25, 50, -1 ],
			[ '25 rows', '50 rows', 'Show all' ]
		],
		columnDefs: [ {
			visible: false
		} ],
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-files-o"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-file-excel-o"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="fa fa-file-pdf-o"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-print"></i> Print',
				titleAttr: 'Print'
			},
			'pageLength','colvis'
		],
		select:true
	} );
	$('select#region').on('change',function(){
		$.post(
			"<?php echo $this->url('employee', array('action' => 'getlocation'));?>",
			{
				regionId: $(this).val(),
			},
			function(data){
				$('select#location').html(data.location);
				$('select#location').trigger('chosen:updated');
			},
			'json'
		);
	});	
</script>​


