<?php
/**
 *  pay head report---Hr/ReportController/gisAction  
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'gis')); ?><br/>
<?php
	extract($data);
?>

<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Group Insurence Schemes
		</h4>
	</div>	
	<div class="widget-body">
		<div class="widget-main">
		<form method="post" action="<?php echo $this->url('preport', array('action' => 'gis')); ?>" >
				<div class="row">
					<div class="col-lg-2">
						<label for="year" class="control-label">Year </label>
						<select class="form-control" name="year" id="year" data-placeholder="Select" required >
							<option value=""></option>
							<?php $minYear = $this->payrollObj->getMin('year');
                            $minYear = ($this->minYear > 0)?$this->minYear:date('Y');?>
							<?php for($y=date('Y');$y >= $minYear; $y--):
								$selected = ($year == $y)?'selected':'';?>
								<option value="<?php echo $y;?>" <?php echo $selected;?>>
									<?php echo $y; ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="month" class="control-label">Month </label>
						<select class="form-control" name="month" id="month" data-placeholder="Select" required >
							<option value=""></option>
							<?php 
								for($m=1;$m<=12;$m++):
									$selected = ($month == $m)?'selected':'';
							?>
								<option value="<?php echo $m;?>" <?php echo $selected;?>>
									<?php echo date("F", strtotime(date("d-$m-y"))); ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					
					<div class="col-md-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data_region)?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $location):
							?>
								<?php $selected = ($location['id'] == $data_location)?'selected':'';?>
								<option value="<?php echo $location['id'];?>" <?php echo $selected;?>>
									<?php echo $location['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2"></br>
						<div class="pull-right">
							<label for="redirect" class="control-label">&nbsp;</label>
							<button type="submit" class="btn btn-sm btn-success"><i class="fa fa-refresh"></i> refresh </button>
						</div>
					</div>
				</div>
			</form>
			<div class="space-12"></div>
			<div class="row">
				<div class="col-lg-12">
				    <input type="hidden" name="gis_date" id="gis_date" value="<?php echo date("F", strtotime(date("d-$month-y"))).','.$data['year'];?>" />
					<strong>For the Month of : <?php echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $year; ?>
					<?php 
						if($data_location > 0):
							$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
						elseif($data_region > 0):
							$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
						else:
							$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year));
						endif;
						if(sizeof($payrolls) > 0):
							//Payroll Generated
						else:
							if($data_location > 0):
								$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
							elseif($data_region > 0):
								$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
							else:
								$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year));
							endif;
							if(sizeof($temp_payrolls) > 0)://Draft?>
								<span class="label label-danger">DRAFT</span>
					<?php	else: //Not Generated ?>
								<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
					<?php	endif;
						endif;
					?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<div class="space-6"></div>
			<table class="table table-condensed table-bordered" id="example">
				<thead>
					<tr>
						<th>Sr. No.</th>
						<th>Emp. No.</th>
						<th>GIS Account No.</th>
						<th>Employee Name</th>
						<th>Designation</th>
						<th>Grade</th>
						<th>Date of Join</th>
						<th>Amount</th>
						<th>ID Card No</th>
						<th>Service Status</th>
						<th>Birth Date</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					$i = 1;
					$sum = array();
					if($data_location > 0):
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
					elseif($data_region > 0):
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
					else:
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year));
					endif;
					if(sizeof($payrolls) > 0):
					foreach($payrolls as $payroll):?>
						<?php $pay_heads = $this->payheadObj->get(6);
							foreach($pay_heads as $payhead):
								$amt = $this->paydetailObj->getColumn(array('pay_roll'=> $payroll['id'], 'pay_head' =>$payhead['id']),'amount');
								$accno = $this->paydetailObj->getColumn(array('pay_roll'=> $payroll['id'], 'pay_head' =>$payhead['id']),'ref_no');
								$remark = $this->paydetailObj->getColumn(array('pay_roll'=> $payroll['id'], 'pay_head' =>$payhead['id']),'remarks');
								$group = $this->paygroupObj->getColumn(array('value'=> round($amt), 'pay_head' =>$payhead['id']),'group');
								$sum_payhead = $this->paystructureObj->getSum('amount',array('pay_head' =>$payhead['id']));
							endforeach;	
						?>
						<?php if($amt > 0):?>
							<tr>
							    <td><?php echo $i++;?></td>
								<td><?php echo $employeeObj->getColumn($payroll['employee_id'],'emp_id');?></td>
								<td><?php if($accno > 0):echo $accno;else:$accno = '--'; echo $accno;endif;?></td>
								<td><?php echo $payroll['full_name'];?></td>
								<td><?php echo $payroll['position_title'];?></td>
								<td><?php echo $payroll['position_level'];?></td>
								<td><?php echo $payroll['office_order_date'];?></td>
								<td><?php if($amt > 0):echo $amt;else:$namt = '--'; echo $namt;endif;?></td>
								<td><?php echo $employeeObj->getColumn($payroll['employee'],'cid');?></td>
								<td><?php echo $payroll['type'];?></td>
								<td><?php echo $employeeObj->getColumn($payroll['employee_id'],'dob');?></td>
							</tr>
						<?php endif;
					endforeach; 
					else:
						if($data_location > 0):
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
						elseif($data_region > 0):
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
						else:
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year));
						endif;
						if(sizeof($temp_payrolls) > 0):
							foreach($temp_payrolls as $temp_payroll):
								
								$pay_heads = $this->payheadObj->get(6);
								foreach($pay_heads as $payhead):
									$amt = $this->paystructureObj->getColumn(array('employee'=> $temp_payroll['employee_id'], 'pay_head' =>$payhead['id']),'amount');
									$accno = $this->paystructureObj->getColumn(array('employee'=> $temp_payroll['employee_id'], 'pay_head' =>$payhead['id']),'ref_no');
									$remark = $this->paystructureObj->getColumn(array('employee'=> $temp_payroll['employee_id'], 'pay_head' =>$payhead['id']),'remarks');
									$group = $this->paygroupObj->getColumn(array('value'=> round($amt), 'pay_head' =>$payhead['id']),'group');
									$sum_payhead = $this->paystructureObj->getSum('amount',array('pay_head' =>$payhead['id']));
								endforeach;
								if($amt > 0):
					?>
							<tr>
								<td><?php echo $i++;?></td>
								<td><?php echo $employeeObj->getColumn($temp_payroll['employee_id'],'emp_id');?></td>
								<td><?php if($accno > 0):echo $accno;else:$accno = '--'; echo $accno;endif;?></td>
								<td><?php echo $temp_payroll['full_name'];?></td>
								<td><?php echo $temp_payroll['position_title'];?></td>
								<td><?php echo $temp_payroll['position_level'];?></td>
								<td><?php //echo $temp_payroll['office_order_date'];?></td>
								<td> <?php if($amt > 0):echo $amt;else:$namt = '--'; echo $namt;endif;?></td>
								<td><?php echo $employeeObj->getColumn($temp_payroll['employee_id'],'cid');?></td>
								<td><?php echo $temp_payroll['type'];?></td>
								<td><?php echo $employeeObj->getColumn($temp_payroll['employee_id'],'dob');?></td>
							</tr>
					             <?php 			
				                endif;
							endforeach;
						endif;
					endif;?>
					</tbody>
					<tfoot>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td><b>Total<b></td>
							<td> <b><?php if(empty($payhead['id'])):echo " ";else: echo $sum_payhead;endif;?> <b></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
                    </tfoot>					
			</table>
	    </div>
	</div>
</div>
<script type="text/javascript">
	var title_table = 'GIS for the Month : '+$('#gis_date').val();
	$('#example').DataTable( {
		dom: 'Bfrtip',
		/*buttons: [
			'copy', 'csv', 'excel', 'pdf', 'print'
		]*/
		lengthMenu: [
			[ 25, 50, -1 ],
			[ '25 rows', '50 rows', 'Show all' ]
		],
		columnDefs: [ {
			visible: false
		} ],
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-files-o"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-file-excel-o"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="fa fa-file-pdf-o"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-print"></i> Print',
				titleAttr: 'Print'
			},
			'pageLength','colvis'
		],
		select:true
	} );
	$('select#region').on('change',function(){
			$.post(
				"<?php echo $this->url('employee', array('action' => 'getlocation'));?>",
				{
					regionId: $(this).val(),
				},
				function(data){
					$('select#location').html(data.location);
					$('select#location').trigger('chosen:updated');
				},
				'json'
			);
		});
	$('form select').chosen({ allow_single_deselect: true });
</script>
