<?php
/**
 *  pay head report---Hr/ReportController/gisAction  
 */
	$this->headTitle($this->title);
	$minYear = ($this->minYear > 0)?$this->minYear:date('Y');
	//echo '<pre>';print_r($data);exit;
    $payrolls = $this->payrollObj->getforReportByLocs($data);
    $temp_payrolls = $this->temppayrollObj->getforReportByLoc($data);
?>
<?php //echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'pfreport')); ?><br/>
<?php echo $this->tabs_helper(array(922,924,925,930,931,932,923,933)); ?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			TDS & HC Report
		</h4>
	</div>	
	<div class="widget-body">
		<div class="widget-main">
			<form method="post" action="<?php echo $this->url('preport', array('action' => 'hctdsreport')); ?>" >
				<div class="row">
					<div class="form-group col-lg-2">
						<label for="year" class="control-label">Year</label>
						<select id="year" name="year" class="form-control" data-placeholder="Select">
							<?php 
							for($year=date('Y');$year >= $minYear;$year--):
							?>
								<?php $selected = ($year == $data['year'])?"selected":"";?>
								<option value="<?php echo $year;?>" <?php echo $selected;?>>
									<?php echo $year;?> 
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="month" class="control-label">Month</label>
						<select id="month" name="month" class="form-control" data-placeholder="Select">
							<?php for($month=1; $month<13; $month++):?>
								<?php $selected = ($month == $data['month'])?'selected':'';?>
								<option value="<?php echo $month;?>" <?php echo $selected; ?>>
									<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
								</option> 
							<?php endfor;?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data['region'])?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $locations):
							?>
								<?php $selected = ($locations['id'] == $data['location'])?'selected':'';?>
								<option value="<?php echo $locations['id'];?>" <?php echo $selected;?>>
									<?php echo $locations['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2 pull-right">
						<div class="space-10"></div>
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="submit" class="btn btn-sm btn-success"><i class="fa fa-refresh"></i> refresh </button>
					</div>
				</div>
			</form>
			<div class="row"><div class="space-12"></div></div>
            <div class="row">
				<div class="col-lg-12">
				    <input type="hidden" name="pf_date" id="pf_date" value="<?php echo date("F", strtotime(date("d-$month-y"))).','.$data['year'];?>" />
					<strong>For the Month of : <?php $month = $data['month']; echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $data['year']; ?>
					<?php
						
						if(sizeof($payrolls) > 0):
							//Payroll Generated
						else:
							
							if(sizeof($temp_payrolls) > 0)://Draft?>
					<span class="label label-danger">DRAFT</span>
					<?php	else: //Not Generated ?>
								<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
					<?php	endif;
						endif;
					?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>
            <div class="space-12"></div>
			<table class="table table-condensed table-bordered" id="hctds">
				<thead>
					<tr>
						<th rowspan=2>Name of Employee</th>
						<th rowspan=2>TPN</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
						<th>5</th>
						<th>6</th>
						<th>7</th>
						<th>8</th>
						<th>9</th>
						<th>10</th>
					</tr>
                    <tr>
						<th>Basic Salary</th>
						<th>Benefit / Allowance</th>
						<th>Salary Arrear</th>
						<th>Gross Salary</th>
						<th>Provident Fund (PF)</th>
						<th>Group Insurance Scheme (GIS)</th>
						<th>Net Salary ( Gross Salary - (PF+GIS))</th>
						<th>TDS On Net Salary</th>
						<th>Health Contribution ( 1% of Gross Salary)</th>
						<th>Total (8+9)</th>
					</tr>
				</thead>
                <tbody>
					<?php 
					$i =1; $tot_tds=0;$tot_hc=0;
					if(sizeof($payrolls) > 0):
					    foreach($payrolls as $payroll):?>
						
                            <tr>
                                <td><?php echo $payroll['full_name'];?></td>
                                <td><?php $tpn = $this->tpnObj->get(array('employee' => $payroll['employee_id']));
								foreach($tpn as $tpns);
								echo (!empty($tpn))?$tpns['tpn']: " "; ?></td>
                                <td><?php $bs=$this->paydetailObj->getColumn(array('pay_roll'=>$payroll['id'],'pay_head'=>1),'amount');$bsa=(!empty($bs))?$bs:0.00;echo number_format((float)$bsa,2,'.',',');?></td>
                                <td><?php $oa=$this->paydetailObj->getAllow(array('pay_roll'=>$payroll['id']),'amount'); if(!empty($oa)){foreach($oa as $oas);
                                    $oass=$oas['amount'];}else{echo $oass=0.00;}echo number_format((float)$oass,2,'.',',');?></td>
                                <td>0.00</td>
                                <td><?php $gross= $bsa+$oass;echo number_format((float)$gross,2,'.',',');?></td>
                                <td><?php $pf=$this->paydetailObj->getColumn(array('pay_roll'=>$payroll['id'],'pay_head'=>9),'amount');$pfd=(!empty($pf))?$pf:0.00;echo number_format((float)$pfd,2,'.',',');?></td>
                                <td><?php $gis=$this->paydetailObj->getColumn(array('pay_roll'=>$payroll['id'],'pay_head'=>12),'amount');$gisd=(!empty($gis))?$gis:0.00;echo number_format((float)$gisd,2,'.',',');?></td>
                                <td><?php echo number_format((float)$gross-($gisd+$pfd),2,'.',',')?></td>
                                <td><?php $td=$this->paydetailObj->getColumn(array('pay_roll'=>$payroll['id'],'pay_head'=>11),'amount');$tds=(!empty($td))?$td:0.00; echo number_format((float)$tds,2,'.',',');?></td>
                                <td><?php $hc=$this->paydetailObj->getColumn(array('pay_roll'=>$payroll['id'],'pay_head'=>14),'amount');$hcd=(!empty($hc))?$hc:0.00;echo number_format((float)$hcd,2,'.',',');?></td>
                               <td><?php echo number_format((float)$tds+$hcd,2,'.',',')?></td>
                            </tr>
                    <?php $tot_tds+=$tds;$tot_hc+=$hcd;endforeach;?>
                    <?php 
					$i =1;
					elseif(sizeof($temp_payrolls) > 0):
					    foreach($temp_payrolls as $temp):?>
                            <tr>
                                <td><?php echo $temp['full_name'];?></td>
                                <td><?php $tpn = $this->tpnObj->get(array('employee' => $temp['employee_id']));
								foreach($tpn as $tpns);
								echo (!empty($tpn))?$tpns['tpn']: " "; ?></td>
                                <td><?php $bs=$this->paystructureObj->getColumn(array('employee'=>$temp['employee_id'],'pay_head'=>1),'amount');$bsa=(!empty($bs))?$bs:0.00;echo number_format((float)$bsa,2,'.',',');?></td>
                                <td><?php $oa=$this->paystructureObj->getAllow(array('employee'=>$temp['employee_id']),'amount'); if(!empty($oa)){foreach($oa as $oas);
                                    $oass=$oas['amount'];}else{echo $oass=0.00;}echo number_format((float)$oass,2,'.',',');?></td>
                                <td>0.00</td>
                                <td><?php $gross= $bsa+$oass;echo number_format((float)$gross,2,'.',',');?></td>
                                <td><?php $pf=$this->paystructureObj->getColumn(array('employee'=>$temp['employee_id'],'pay_head'=>9),'amount');$pfd=(!empty($pf))?$pf:0.00;echo number_format((float)$pfd,2,'.',',');?></td>
                                <td><?php $gis=$this->paystructureObj->getColumn(array('employee'=>$temp['employee_id'],'pay_head'=>12),'amount');$gisd=(!empty($gis))?$gis:0.00;echo number_format((float)$gisd,2,'.',',');?></td>
                                <td><?php echo number_format((float)$gross-($gisd+$pfd),2,'.',',')?></td>
                                <td><?php $td=$this->paystructureObj->getColumn(array('employee'=>$temp['employee_id'],'pay_head'=>11),'amount');$tds=(!empty($td))?$td:0.00; echo number_format((float)$tds,2,'.',',');?></td>
                                <td><?php $hc=$this->paystructureObj->getColumn(array('employee'=>$temp['employee_id'],'pay_head'=>14),'amount');$hcd=(!empty($hc))?$hc:0.00;echo number_format((float)$hcd,2,'.',',');?></td>
                               <td><?php echo number_format((float)$tds+$hcd,2,'.',',')?></td>
                            </tr>
                    <?php $tot_tds+=$tds;$tot_hc+=$hcd; endforeach;  endif;  ?>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><b>Total</b></td>
                        <td><b><?php echo number_format((float)$tot_tds,2,'.',',');?></b></td>
                        <td><b><?php echo number_format((float)$tot_hc,2,'.',',');?></b></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
	var title_table = 'PTPIT for the Month : '+$('#ptpit_date').val();
	$('select#region').on('change',function(){
		$.post(
			"<?php echo $this->url('employee', array('action' => 'getlocation'));?>",
			{
				regionId: $(this).val(),
			},
			function(data){
				$('select#location').html(data.location);
				$('select#location').trigger('chosen:updated');
			},
			'json'
		);
	});
	$('#hctds').DataTable( {
		paging:true,
		scrollX:true,
		dom: 'Bfrtip',
		/*buttons: [
			'copy', 'csv', 'excel', 'pdf', 'print'
		]*/
		lengthMenu: [
			[ 25, 50, -1 ],
			[ '25 rows', '50 rows', 'Show all' ]
		],
		columnDefs: [ {
			visible: false
		} ],
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-files-o"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-file-excel-o"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="fa fa-file-pdf-o"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-print"></i> Print',
				titleAttr: 'Print'
			},
			'pageLength','colvis'
		],
		select:true
	} );
	
	$('form select').chosen({ allow_single_deselect: true });
</script>