<?php
/**
 *  pay head report---Hr/ReportController/htpitreport  
 */
	$this->headTitle($this->title);
?>
<?php //echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'htpitreport')); ?>
<?php echo $this->tabs_helper(array(922,924,925,930,931,932,923,933)); ?>
<?php	
	$earningHead = $this->payheadObj->get(array('deduction'=>0));
	$earning=sizeof($earningHead)-6; //no of earning columns
	//$earning = $earning - 1;
	$count=0;
	for($i=0;$i<sizeof($role);$i++){
		if($role[$i]==99 || $role[$i]==100){
			$count=1;
			break;
		}
		else{
			$count=0;
		}
	}
	
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Health Tax & Personal Income Tax Report
		</h4>
		<div class="pull-right tableTools-container"></div>
	</div>	
	<div class="widget-body">
		<div class="widget-main">
		<form method="post" action="<?php echo $this->url('preport', array('action' => 'htpitreport')); ?>" >
				<div class="row">
					<div class="col-md-2">
						<label for="year" class="control-label">Year </label>
						<select class="form-control" name="year" id="year" data-placeholder="Select" required >
							<option value="2024">2024</option>
							<?php $minYear = $this->payrollObj->getMin('year');
                            $minYear = ($this->minYear > 0)?$this->minYear:date('Y');?>
							<?php for($y=date('Y');$y >= $minYear; $y--):
								$selected = ($data['year'] == $y)?'selected':'';?>
								<option value="<?php echo $y;?>" <?php echo $selected;?>>
									<?php echo $y; ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="month" class="control-label">Month </label>
						<select class="form-control" name="month" id="month" data-placeholder="Select" required >
							<option value=""></option>
							<?php 
								for($m=1;$m<=12;$m++):
									$selected = ($data['month'] == $m)?'selected':'';
							?>
								<option value="<?php echo $m;?>" <?php echo $selected;?>>
									<?php echo date("F", strtotime(date("d-$m-y"))); ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data['region'])?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $location):
							?>
								<?php $selected = ($location['id'] == $data['location'])?'selected':'';?>
								<option value="<?php echo $location['id'];?>" <?php echo $selected;?>>
									<?php echo $location['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-4">
						<div class="space-10"></div>
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="submit" class="btn btn-sm btn-success"><i class="fa fa-refresh"></i> Generate </button>				
					</div>
					<?php //if($count==1):?>
						<div class="btn-group pull-right">
						<?php echo $this->button(2);?>
					</div>
					<?php //endif;?>
				</div>
			</form>
			<div class="row"><div class="space-12"></div></div>
			<div class="row">
				<div class="col-lg-12">
					<input type="hidden" name="ptpit_date" id="ptpit_date" value="<?php echo date("F", strtotime(date("d-$month-y"))).','.$data['year'];?>" />
					<strong>For the Month of : <?php $month = $data['month']; echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $data['year']; ?>
					<?php
						$filter = array(
							'year'=>$data['year'], 
							'month'=>$data['month'], 
							'pr.status'=>'1'									
						);
						if($data['region'] > 0):
							$filter['l.region'] = $data['region']; 
						endif;
						if($data['location'] > 0):
							$filter['e.location'] = $data['location']; 
						endif;
						$payrolls = $this->payrollObj->getforReport($filter);
						if(sizeof($payrolls) > 0):
							//Payroll Generated
						else:
							$temp_payrolls = $this->temppayrollObj->getforReport($filter);
							if(sizeof($temp_payrolls) > 0)://Draft?>
					<span class="label label-danger">DRAFT</span>
					<?php	else: //Not Generated ?>
								<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
					<?php	endif;
						endif;
					?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<div class="space-12"></div>
			<div style="overflow: auto;">
			<table class="table table-condensed table-bordered" id="htpi">
				<thead>
					<tr>
						<th rowspan="2">#</th>
						<th rowspan="2">NAME OF EMPLOYEE</th>
						<th rowspan="2">CID NO.</th>
						<th rowspan="2">TAX PAYER NO.</th>
						<th rowspan="2">BASIC SALARY</th>
						<th colspan="<?php echo $earning;?>" style="text-align:center">ALLOWANCES</th>
						<th rowspan="2">GROSS SALARY</th>
						<th rowspan="2">SALARY TAX</th>
						<th rowspan="2">HEALTH CONTRIB.</th>
						<th rowspan="2">TOTAL TAX</th>
						<th rowspan="2">Remarks</th>
						<th rowspan="2">Action</th>
					</tr>
					<tr>
						<!-- Earnings columns -->
						<?php foreach($earningHead as $row):
							if($row['id']!=1 && $row['id']!=2 && $row['id']!=10 && $row['id']!=45 && $row['id']!=46 && $row['id']!=47):?>
								<th><?php echo $row['code'];?></th>
						<?php endif;
							endforeach;?> 
					</tr>
				</thead>
				<tbody>
					<?php $i = 1; 
					$filter = array(
							'year'=>$data['year'], 
							'month'=>$data['month'], 
							'pr.status'=>'1'									
					);
					if($data['region'] > 0):
						$filter['l.region'] = $data['region']; 
					endif;
					if($data['location'] > 0):
						$filter['e.location'] = $data['location']; 
					endif;
					$tot_earning = array();
					$tot_deduction = array();
					$tot_basic_salary = 0;
					$tot_gross_salary = 0;
					$tot_salary_tax = 0;
					$tot_health_tax = 0;
					$tot_total_tax = 0;
					$pay_rolls = $this->payrollObj->getforReport($filter);
					//echo '<pre>';print_r($pay_rolls);exit;
					if(sizeof($pay_rolls) > 0):
					foreach ($pay_rolls as $pay_roll):?>
						<tr>
							<td style="border-top: 1px solid #5add55;"><?php echo $i++; ?> </td>
							<td style="border-top: 1px solid #5add55;" ><?php echo $pay_roll['full_name']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php echo $pay_roll['cid']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$pit_tax_no = $this->tpnObj->get(array('employee' => $pay_roll['employee']));
								foreach($pit_tax_no as $tpns);
								echo (!empty($pit_tax_no))?$tpns['tpn']: " ";
								
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$basic_salarys = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '1'), 'amount');
								if(!empty($basic_salarys)):
									echo $basic_salary=$basic_salarys;
								else:
									echo $basic_salary= 0.00;
								endif;
								$tot_basic_salary +=$basic_salary;
							?></td>
							<!-- values for earning column -->
							<?php foreach ($earningHead as $key => $row): if($row['id']!=1 && $row['id']!=2 && $row['id']!=10 && $row['id']!=45 && $row['id']!=46 && $row['id']!=47):?>
								<td style="border-top: 1px solid #5add55;"><?php
									$amount = (int)$this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									//$tot_earning[$key] += $amount;
								?></td>
							<?php endif; endforeach;?>
							<td style="border-top: 1px solid #5add55;">
							<?php
								$gross_salary = (int)$this->payrollObj->getColumn(array('employee' => $pay_roll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'gross');
								echo $this->decimal($gross_salary);
								$tot_gross_salary +=$gross_salary;
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$salary_tax = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '11'), 'amount');
								if(empty($salary_tax)):
									echo $salary_taxes=0;
								else:
									echo $salary_taxes=$salary_tax;
								endif;
								$tot_salary_tax +=$salary_taxes;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								$health_tax = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '16'), 'amount');
								if(empty($health_tax)):
									echo $health_taxes=0;
								else:
									echo $health_taxes=$health_tax;
								endif;
								$tot_health_tax +=$health_taxes;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								$total_tax=((int)$salary_taxes + (int)$health_taxes);
								echo $this->decimal($total_tax);
								$tot_total_tax +=$total_tax;
							?></td>
							<td><?php //echo $this->voucher->getColumn(array('year'=>$data['year'],'month'=>$data['month']),'voucher');?></td>
							<td><?php echo $this->button(1,$pay_roll['employee'].'-'.$data['year']);?></td>
						</tr>
					<?php endforeach;
					else:
					$temp_payrolls = $this->temppayrollObj->getforReport($filter);
					foreach($temp_payrolls as $temp_payroll):
					?>
						<tr>
							<td style="border-top: 1px solid #5add55;" ><?php echo $i++; ?> </td>
							<td style="border-top: 1px solid #5add55;"><?php echo $temp_payroll['full_name']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php echo $temp_payroll['cid']; ?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$pit_tax_no = $this->tpnObj->get(array('employee' => $temp_payroll['employee_id']));
								foreach($pit_tax_no as $tpns);
								echo (!empty($pit_tax_no))?$tpns['tpn']: " ";
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$basic_salary = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '1'), 'amount');
								 $basic_salary=(!empty($basic_salary))?$basic_salary:0.00;
								 echo $this->decimal($basic_salary);
								$tot_basic_salary +=$basic_salary;
							?></td>
							<!-- values for earning column -->
							<?php foreach ($earningHead as $key => $row): if($row['id']!=1 && $row['id']!=2 && $row['id']!=10 && $row['id']!=45 && $row['id']!=46 && $row['id']!=47):?>
								<td style="border-top: 1px solid #5add55;"><?php
									$amount = (int)$this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$expense_amt = $this->paystructureObj->getSum('amount',array('pay_head' => $row['id']));
									//$tot_earning[$key] += $amount;
								?></td>
							<?php endif; endforeach;?>
							<td style="border-top: 1px solid #5add55;">
							<?php
								$gross_salary = (int)$this->temppayrollObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'gross');
								echo $this->decimal($gross_salary);
								$tot_gross_salary +=$gross_salary;
							?></td>
							<td style="border-top: 1px solid #5add55;"><?php 
								$salary_tax = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '11'), 'amount');
								if(empty($salary_tax)):echo 0.00;else:echo $this->decimal($salary_tax);endif;
								$tot_salary_tax = $this->paystructureObj->getSum('amount',array('pay_head' => '11'));
								//$tot_salary_tax +=$salary_tax;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								$health_tax = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '16'), 'amount');
								if(empty($health_tax)):echo 0.00;else:echo $this->decimal($health_tax);endif;
								$tot_health_tax = $this->paystructureObj->getSum('amount',array('pay_head' => '16'));
								//$tot_health_tax +=$health_tax;
							?></td>
							 <td style="border-top: 1px solid #5add55;"><?php 
								//$total_tax = $salary_tax + $health_tax;
								$total_tax=((int)$salary_tax + (int)$health_tax);
								echo $this->decimal($total_tax);
								$tot_total_tax +=$total_tax;
							?></td>
							<td></td>
							<td></td>
						</tr>
					<?php endforeach;
					endif;?>	
				     <tr>
						<td></td>
						<td></strong></td>
						<td></td>
						<td> <strong>Total:   </strong></td>
						<td><strong><?php echo $this->decimal($tot_basic_salary);?></strong></td>
						<!-- values for earning column -->
						<?php foreach($earningHead as $key => $row): if($row['id']!=1 && $row['id']!=2 && $row['id']!=10 && $row['id']!=45 && $row['id']!=46 && $row['id']!=47):
							$expense_amt = $this->paystructureObj->getSum('amount',array('pay_head' => $row['id']));?>
							<td><strong><?php echo $this->decimal($expense_amt); ?></strong></td>
						<?php endif; endforeach;?>
						<td><strong><?php echo $this->decimal($tot_gross_salary);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_salary_tax);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_health_tax);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_total_tax);?></strong></td>
						<td></td>
						<td></td>
						
					</tr>
				</tbody>
			</table></div>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
	var title_table = 'PTPIT for the Month : '+$('#ptpit_date').val();
	$('select#region').on('change',function(){
		$.post(
			"<?php echo $this->url('employee', array('action' => 'getlocation'));?>",
			{
				regionId: $(this).val(),
			},
			function(data){
				$('select#location').html(data.location);
				$('select#location').trigger('chosen:updated');
			},
			'json'
		);
	});
	$('#htpi').DataTable( {
		paging:true,
		scrollX:true,
		dom: 'Bfrtip',
		/*buttons: [
			'copy', 'csv', 'excel', 'pdf', 'print'
		]*/
		lengthMenu: [
			[ 25, 50, -1 ],
			[ '25 rows', '50 rows', 'Show all' ]
		],
		columnDefs: [ {
			visible: false
		} ],
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-files-o"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-file-excel-o"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="fa fa-file-pdf-o"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-print"></i> Print',
				titleAttr: 'Print'
			},
			'pageLength','colvis'
		],
		select:true
	} );
	
	$('form select').chosen({ allow_single_deselect: true });
</script>
