<?php
/**
 *  pay head report---Hr/ReportController/phreportAction  
 */
	$this->headTitle($this->title);
	 
?>
<?php //echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'loanreport')); ?>
<?php echo $this->tabs_helper(array(922,924,925,930,931,932,923,933)); ?>
<?php
//extract($this->data);
//echo '<pre>';print_r($payroll);exit;
$minYear = ($this->minYear > 0)?$this->minYear:date('Y');
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Remittance Report
		</h4>
	</div>
	<div class="widget-body">
		<div class="widget-main">
			<div class="row"><div class="space-12"></div></div>
			<form method="post" action="<?php echo $this->url('preport', array('action' => 'loanreport')); ?>" >
				<div class="row">
					<div class="form-group col-lg-2">
						<label for="year" class="control-label">Year</label>
						<select id="year" name="year" class="form-control" data-placeholder="Select">
							<?php 
							for($year=date('Y');$year >= $minYear;$year--):
							?>
								<?php $selected = ($year == $data['year'])?"selected":"";?>
								<option value="<?php echo $year;?>" <?php echo $selected;?>>
									<?php echo $year;?> 
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="month" class="control-label">Month</label>
						<select id="month" name="month" class="form-control" data-placeholder="Select">
							<?php for($month=1; $month<13; $month++):?>
								<?php $selected = ($month == $data['month'])?'selected':'';?>
								<option value="<?php echo $month;?>" <?php echo $selected; ?>>
									<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
								</option> 
							<?php endfor;?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data['region'])?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $locations):
							?>
								<?php $selected = ($locations['id'] == $data['location'])?'selected':'';?>
								<option value="<?php echo $locations['id'];?>" <?php echo $selected;?>>
									<?php echo $locations['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="payhead" class="control-label">Pay Head(Dedution)</label>
						<select class="form-control chosen-select tag-input-style" id="payhead" name="payhead" data-placeholder="Choose a Pay Head...">
							<?php foreach($this->payheadObj->get(array('pht.deduction'=>1)) as $ph): 
							?>
								<option value="<?php echo $ph['id'];?>" <?php echo ($ph['id']==$data['payheads'])? 'selected':'';?> > <?php echo $ph['pay_head'];?> </option>
							<?php endforeach; ?>
						</select>
					</div>
					<div class="col-md-1">
						<label for="redirect" class="control-label"> &nbsp;</label></br>
						<button type="submit" class="btn btn-sm btn-success"><i class="fa fa-refresh"></i> refresh </button>
					</div>
				</div>
			</form>
			<div class="space-12"></div>
			<div class="row">
				<div class="col-lg-12">
					<strong>Report On :
						<?php echo $this->payheadObj->getColumn($payheads,'pay_head');?>
				</strong>
				</div>
			</div>
			<div class="row">
			<?php $month = $data['month'];$year = $data['year'];?>
				<div class="col-lg-12" align="center">
				    <input type="hidden" name="ph_date" id="ph_date" value="<?php echo date("F", strtotime(date("d-$month-y"))).','.$data['year'];?>" />
					<strong>For the Month of : <?php echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $year; ?>
						<?php 
							 $temp_payrolls= $this->temppayrollObj->getforReportByLoc($data);
								if(sizeof($temp_payrolls) > 0)://Draft?>
									<span class="label label-danger">DRAFT</span>
						<?php	elseif(empty($payroll) && empty($temp_payrolls)): //Not Generated ?>
									<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
						<?php	endif;?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>
			<div class="space-12"></div>
			<table class="table table-condensed table-bordered" id="example">
			<thead>
					<tr >
						<th>Sl. No.</th>
						<th>Emp. No.</th>
						<th>DOB</th>
						<th>Employee Name</th>
						<th>CID No.</th>
						<th>Deduction Type</th>
						<th>Amount</th>
						<th>A/c Number</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1;$total=0;if(!empty($payroll)):
					?>
						<?php foreach($payroll as $pr):
							//$paydetail_id = $this->paydetailObj->getColumn(array('pay_roll'=> $pr['id'], 'pay_head' =>$payheads),'id');
							
							$tpnID=$this->tpnObj->get(['employee'=>$pr['employee']]);
							foreach($tpnID as $tpna)
							$tpn =$tpna['tpn'];
							$pf =$tpna['pf'];
							$gis =$tpna['gis'];
							if($payheads=='12'){
								$acc=$gis;
							}
							if($payheads=='9'){
								$acc=$pf;
							}
							//echo '<pre>';print_r($acc);
							//echo '<pre>';print_r($payroll);exit;
							?>
					<tr>
						<td><?php echo $i++;?></td>
						<td><?php echo $pr['emp_id'];?></td>
						<td><?php echo $pr['dob'];?></td>
						<td><?php echo $pr['full_name'];?></td>
						<td><?php echo $pr['cid'];?></td>
						<td><?php echo $this->payheadObj->getColumn(array('id' =>$payheads),'pay_head');?></td>
						<td><?php  //echo $pr['actual_amount'];
						// $amount=(!empty($amt))?$amt:0.00;
						 echo number_format((float)$pr['actual_amount'],2,'.',',');?></td>
						<td><?php if($payheads=='12'||$payheads=='9'):
										echo $acc;
									else:
										echo $pr['ref_no'];
									endif;?></td>
					</tr>
					<?php $total+=$pr['actual_amount'];endforeach;?>
					<?php else: $temp= $this->temppayrollObj->getforReportByLoc($data);
					foreach($temp as $temps)://echo '<pre>';print_r($temp);exit;?>
					<tr>
						<td><?php echo $i++;?></td>
						<td><?php echo $temps['emp_id'];?></td>
						<td><?php echo $temps['dob'];?></td>
						<td><?php echo $temps['full_name'];?></td>
						<td><?php echo $temps['cid'];?></td>
						<td><?php echo $this->payheadObj->getColumn(array('id' =>$payheads),'pay_head');?></td>
						<td><?php $amt  = $this->paystructureObj->getColumn(array('employee'=> $temps['employee_id'], 'pay_head' =>$payheads),'amount');
						 $amount=(!empty($amt))?$amt:0.00;
						 echo number_format((float)$amount,2,'.',',');?></td>
						<td></td>
					</tr>
					<?php $total+=$amount;endforeach;endif;?>
				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td></td>
						<td></td>
					   	<td></td>
						<td><b>Total:</b></td>
						<td><b><?php echo number_format((float)$total,2,'.',','); ?></b></td>
						<td></td>

					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
	var title_table = 'PH for the Month : '+$('#ph_date').val();
	$('#example').DataTable( {
		dom: 'Bfrtip',
		/*buttons: [
			'copy', 'csv', 'excel', 'pdf', 'print'
		]*/
		lengthMenu: [
			[ 25, 50, -1 ],
			[ '25 rows', '50 rows', 'Show all' ]
		],
		columnDefs: [ {
			visible: false
		} ],
		buttons: [
			{
				extend: 'copy',
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-files-o"></i> Copy',
				titleAttr: 'Copy'
			},
			{
				extend: 'excel',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-file-excel-o"></i> Excel',
				titleAttr: 'Excel'
			},
			{
				extend: 'pdfHtml5',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				orientation: 'landscape',
				pageSize: 'LEGAL',
				text: '<i class="fa fa-file-pdf-o"></i> Pdf',
				titleAttr: 'PDF'
			},
			{
				extend: 'print',
				title: title_table,
				exportOptions: {
					columns: ':visible'
				},
				text: '<i class="fa fa-print"></i> Print',
				titleAttr: 'Print'
			},
			'pageLength','colvis'
		],
		select:true
	} );
	$('select#region').on('change',function(){
		$.post(
			"<?php echo $this->url('employee', array('action' => 'getlocation'));?>",
			{
				regionId: $(this).val(),
			},
			function(data){
				$('select#location').html(data.location);
				$('select#location').trigger('chosen:updated');
			},
			'json'
		);
	});
	$('form select').chosen({ allow_single_deselect: true });
	
</script>
