<?php
/**
 * 
 * Report -- of Payroll
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'payregister')); ?><br/>
<?php	
	$earning=ceil(count($earningHead)/2); //no of earning columns
	$deduction=ceil(count($deductionHead)/2); //no of deduction columns
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Pay Register
		</h4>
		<div class="widget-toolbar hidden-xs">
			<a style='cursor:pointer' id="print">
				<i class="ace-icon fa fa-file-pdf-o red"></i>
			</a>
		</div>
	</div>
	<div class="widget-body">
		<div class="widget-main">
			<form>
				<div class="row">
					<div class="form-group col-lg-2">
						<label for="year" class="control-label">Year</label>
						<select id="year" name="year" class="form-control" data-placeholder="Select">
							<?php 
							for($year=date('Y');$year >= $this->minYear;$year--):
							?>
								<?php $selected = ($year == $data['year'])?"selected":"";?>
								<option value="<?php echo $year;?>" <?php echo $selected;?>>
									<?php echo $year;?> 
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="month" class="control-label">Month</label>
						<select id="month" name="month" class="form-control" data-placeholder="Select">
							<?php for($month=1; $month<13; $month++):?>
								<?php $selected = ($month == $data['month'])?'selected':'';?>
								<option value="<?php echo $month;?>" <?php echo $selected; ?>>
									<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
								</option> 
							<?php endfor;?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data['region'])?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>        
					<div class="form-group col-lg-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $location):
							?>
								<?php $selected = ($location['id'] == $data['location'])?'selected':'';?>
								<option value="<?php echo $location['id'];?>" <?php echo $selected;?>>
									<?php echo $location['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="form-group col-lg-2">
						<label for="department" class="control-label">Department</label>
						<select class="form-control" id="department" name="department" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($department as $department):
							?>
								<?php $selected = ($department['id'] == $data['department'])?'selected':'';?>
								<option value="<?php echo $department['id'];?>" <?php echo $selected;?>>
									<?php echo $department['department'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div> 
					<div class="form-group col-lg-1">
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="button" class="btn btn-sm btn-info" onclick="refresh()" ><i class="fa fa-refresh"></i> refresh</button>
					</div>
				</div>
			</form>
		<?php if($data['region'] !='' && $data['location'] != '' && $data['department'] != ''):?>
			<div class="row">
				<div class="col-lg-12">
					<?php $month = $data['month'];?>
					<strong>
						<h3>Pay Register for the Month of : <?php echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $data['year']; ?>
						<?php
							$filter = array(
								'year'=>$data['year'], 
								'month'=>$data['month'], 
								'pr.status'=>'1'									
							);
							if($data['region'] > 0):
								$filter['l.region'] = $data['region']; 
							endif;
							if($data['location'] > 0):
								$filter['e.location'] = $data['location']; 
							endif;
							if($data['department'] > 0):
								$filter['e.department'] = $data['department']; 
							endif;
							$pay_rolls = $this->payrollObj->getforReport($filter);
							if(sizeof($pay_rolls) > 0):
								//Payroll is generated
							else:
								$temp_payrolls = $this->temppayrollObj->getforReport($filter);
								if(sizeof($temp_payrolls)>0): //Draft
						?>
							<span class="label label-danger">DRAFT</span>
						<?php else: //Payroll is not Prepared?>
							<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
						<?php	endif;
							endif;
						?>
						</h3>
						<label>  <i class="blue fa fa-globe"></i> Region: </label> <span><?php echo $region = ($data["region"] == -1)? "All": $this->regionObj->getColumn($data["region"], 'region');?></span>
						<label>  <i class="orange fa fa-map-marker"></i> Location: </label> <span><?php echo $loc = ($data["location"] == -1)? "All": $this->locationObj->getColumn($data["location"], 'location');?></span>
						<label>  <i class="blue fa fa-sitemap"></i> Department: </label> <span><?php echo $dept = ($data["department"] == -1)? "All": $this->departmentObj->getColumn($data["department"], 'department');?></span>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<table class="table-condensed table-striped table-bordered table-hover" id="reportTable">
				<thead>
					<tr>
						<th rowspan="2">#</th>
						<th rowspan="2">EmpName<br>EmpNo</th>
						<th rowspan="2">Position<br>Department</th>
						<th rowspan="2">Grade</th>
						<th colspan="<?php echo $earning;?>" style="text-align:center">Earnings</th>
						<th colspan="<?php echo $deduction;?>" style="text-align:center">Deductions</th>
						<th colspan="3" style="text-align:center">Summary</th>
					</tr>
					<tr>
						<!-- Earnings columns -->
						<?php foreach ($this->earningHead as $key => $row):?>
							<?php if($key%2==0):?><th><?php endif; ?>
							<?php echo $row['code'];?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></th><?php endif; ?>
						<?php endforeach;?> 
						
						<!-- Deduction columns -->
						<?php foreach ($this->deductionHead as $key => $row):?>
							<?php if($key%2==0):?><th><?php endif; ?>
							<?php echo $row['code'];?>
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></th><?php endif; ?>
						<?php endforeach;?>								
						<th>Bonus</th>
						<th>Leave Enc</th>
						<th>Net Pay</th>
					</tr>
				</thead>
				<tbody>							
					<?php $i = 1; 
					$sum_amounts = array();
					$filter = array(
							'year'=>$data['year'], 
							'month'=>$data['month'], 
							'pr.status'=>'1'									
					);
					if($data['region'] > 0):
						$filter['l.region'] = $data['region']; 
					endif;
					if($data['location'] > 0):
						$filter['e.location'] = $data['location']; 
					endif;
					if($data['department'] > 0):
						$filter['e.department'] = $data['department']; 
					endif;
					$tot_earning = array();
					$tot_deduction = array();
					$tot_bonus = 0;
					$tot_leave_encashment = 0;
					$tot_net = 0;
					$pay_rolls = $this->payrollObj->getforReport($filter);
					if(sizeof($pay_rolls) > 0):
					foreach ($pay_rolls as $pay_roll):?>
						<tr>
							<td><?php echo $i++; ?> </td>
							<td><?php echo $pay_roll['full_name']; ?> <br><?php echo $pay_roll['emp_id']; ?></td>
							<td><?php echo $pay_roll['position_title'];?> <br> <?php echo $pay_roll['department'];?></td>
							<td><?php echo $pay_roll['position_level'];?></td>
							
							<!-- values for earning column -->
							<?php foreach ($this->earningHead as $key => $row):?>
								<?php if($key%2==0):?><td><?php endif; ?>
								<?php
									$amount = (int)$this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_earning[$key] += $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
							<?php endforeach;?>
							  
							<!-- values for deduction column -->
							<?php foreach ($this->deductionHead as $key => $row):?>
								<?php if($key%2==0):?><td><?php endif; ?>
								<?php
									$amount = (int)$this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_deduction[$key] += $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
							<?php endforeach;?>										 
							 <!-- values form payroll -->
							 <td>
							 <?php
								$bonus = (int)$this->payrollObj->getColumn(array('employee' => $pay_roll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'bonus');
								echo $this->decimal($bonus);
								$tot_bonus += $bonus;
							 ?>
							 </td>
							  <td>
							 <?php
								$leave_encashment = (int)$this->payrollObj->getColumn(array('employee' => $pay_roll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'leave_encashment');
								echo $this->decimal($leave_encashment);
								$tot_leave_encashment +=$leave_encashment;
							 ?>
							 </td>
							 <td>
							 <?php
								$net_pay = (int)$this->payrollObj->getColumn(array('employee' => $pay_roll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'net_pay');
								echo $this->decimal($net_pay);
								$tot_net +=$net_pay;
							 ?>
							 </td>
						</tr>
					<?php endforeach;  
					else:
					$temp_payrolls = $this->temppayrollObj->getforReport($filter);
					foreach($temp_payrolls as $temp_payroll):
					?>
						<tr>
							<td><?php echo $i++; ?></td>
							<td><?php echo $temp_payroll['full_name']; ?> <br><?php echo $temp_payroll['emp_id']; ?></td>
							<td><?php echo $temp_payroll['position_title'];?> <br> <?php echo $temp_payroll['department'];?></td>
							<td><?php echo $temp_payroll['position_level'];?></td>
							
							<!-- values for earning column -->
							<?php foreach ($this->earningHead as $key => $row):?>
								<?php if($key%2==0):?><td><?php endif; ?>
								<?php
									$amount = (int)$this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_earning[$key] += $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
							<?php endforeach;?>
							  
							<!-- values for deduction column -->
							<?php foreach ($this->deductionHead as $key => $row):?>
								<?php if($key%2==0):?><td><?php endif; ?>
								<?php
									$amount = (int)$this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_deduction[$key] += $amount;
								?>											
								<?php if($key%2==0):?><br><?php endif; ?>
								<?php if($key%2!=0):?></td><?php endif; ?> 
							<?php endforeach;?>										 
							 <!-- values form payroll -->
							 <td>
							 <?php
								$bonus = (int)$this->temppayrollObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'bonus');
								echo $this->decimal($bonus);
								$tot_bonus += $bonus;
							 ?>
							 </td>
							  <td>
							 <?php
								$leave_encashment = (int)$this->temppayrollObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'leave_encashment');
								echo $this->decimal($leave_encashment);
								$tot_leave_encashment +=$leave_encashment;
							 ?>
							 </td>
							 <td>
							 <?php
								$net_pay = (int)$this->temppayrollObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'net_pay');
								echo $this->decimal($net_pay);
								$tot_net +=$net_pay;
							 ?>
							 </td>
						</tr>
					<?php endforeach;
					endif;?>
					<tr>
						<td colspan="4" style="text-align:right"> <strong>Total:   </strong></td>
						<!-- values for earning column -->
						<?php foreach ($this->earningHead as $key => $row):?>
							<?php if($key%2==0):?><td><?php endif; ?>
							<strong><?php echo $this->decimal($tot_earning[$key]); ?></strong>											
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>
						  
						<!-- values for deduction column -->
						<?php foreach ($this->deductionHead as $key => $row):?>
							<?php if($key%2==0):?><td><?php endif; ?>
							<strong><?php echo $this->decimal($tot_deduction[$key]); ?>	</strong>										
							<?php if($key%2==0):?><br><?php endif; ?>
							<?php if($key%2!=0):?></td><?php endif; ?> 
						<?php endforeach;?>	
						<td>
							<strong><?php echo $this->decimal($tot_bonus);?></strong>
						</td>
						<td>
							<strong><?php echo $this->decimal($tot_leave_encashment);?></strong>
						</td>
						<td>
							<strong><?php echo $this->decimal($tot_net);?></strong>
						</td>
					</tr>	
				</tbody>
			</table>
		<?php 
			else:
			?>
			<div class="alert alert-success fade in">  
				<strong>Click the Refresh button after selecting required region, location and department</strong>
			 </div>	
			<?php 
			endif;?>
		</div>
	</div>
</div>
	
<script>
	$('#reportTable').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
		caller:"#print"
	});
	$("#region").change(function() { 
		$.post( "<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function( data ) {
			var newdata ="<option value='-1'>All</option>"+data
			$('#location').html( newdata );
			$("#location").trigger('chosen:updated');
		});
	});
	//fuction to refresh 
	function refresh(){
		var id = $('#region').val()+'&'+$('#location').val()+'&'+$('#department').val()+'&'+$('#year').val()+'&'+$('#month').val();
		location.href="<?php echo $this->url('preport', array('action'=>'payregister'));?>/"+id;
	}	
</script>​

