<?php
/**
 * 
 * View -- of Hr/EmployeeController/addfamilyAction
 * 
 */
?>

<form id="#form" method="post" action="<?php echo $this->url('employee', array('action' => 'addfamily', 'id' => $this->id)); ?>"  enctype="multipart/form-data" >    
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i>Family  details</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label for="qualification" class="control-label">Name</label>
					<input type="text" class="form-control" name="name" id="name" required /> 
				</div>
				<div class="form-group">
					<label for="institute" class="control-label">Relation</label>
					<input type="text" class="form-control" name="relation" id="relation" required /> 
				</div>
				<div class="form-group">
					<label for="nationality" class="control-label">Nationality</label>
					<input type="text" class="form-control" name="nationality" id="nationality" required /> 
				</div>
				<div class="form-group">
					<label for="occupation" class="control-label">Occupation</label>
					<input type="text" class="form-control" name="occupation" id="occupation" required /> 
				</div>
				<div class="form-group">
					<label for="address" class="control-label">Address</label>
					<input type="text" class="form-control" name="address" id="address" required /> 
				</div>
				<div class="form-group">
					<label for="remarks" class="control-label">Remarks</label>
					<input type="text" class="form-control" name="remarks" id="remarks" /> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form> 
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			name: {
				validators: {
					notEmpty: {
						message: 'Please provide name.'
					}
				}
			},
			relation: {
				validators: {
					notEmpty: {
						message: 'Please provide relation.'
					}
				}
			},
			nationality: {
				validators: {
					notEmpty: {
						message: 'Please provide nationality.'
					}
				}
			},
			occupation: {
				validators: {
					notEmpty: {
						message: 'Please provide occupation.'
					}
				}
			},
			address: {
				validators: {
					notEmpty: {
						message: 'Please provide address.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>  
