<?php
/**
 * 
 * View -- of Hr/EmphltController/addAction
 * 
 */
?>
<?php foreach ($this->emp as $emprows):
	extract ($emprows);
endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('employee', array('action' => 'addleave', 'id'=> $id)); ?>"  enctype="multipart/form-data" >
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"> <i class="fa fa-asterisk"></i> New Leave Record for <?php echo $full_name; ?></h4>
	</div>  <!-- /modal-header -->
	<div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="leavetype" class="control-label">Type of Leave</label>
					<select class="form-control" id="leave_type" name="leave_type" data-placeholder="-Select-" required >
						<option value=""></option>
						<?php 
						foreach ($leavetype as $leavetype):
						?>
							<option value="<?php echo $leavetype['id'];?>">
								<?php echo $leavetype['type'];?> 
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
				<div class="form-group">
					<label for="no_of_days" class="control-label">No. of Days</label>
					<input type="text" class="form-control" name="no_of_days" id="no_of_days" size="30" required> 
				</div>
				<div class="form-group">
					<label for="sanction" class="control-label">Sanction Order no.</label>
					<input type="text" class="form-control" name="sanction_order_no" id="sanction_order_no" size="30" required> 
				</div>
			
				<div class="form-group col-lg-6">
					<label for="start_date" class="control-label">Start Date</label>
					<div class="date input-group" id="start_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-6">
					<label for="end_date" class="control-label">End Date</label>
					<div class="date input-group" id="end_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="remarks" class="control-label">Remarks</label>
					<textarea class="form-control" name="remarks" id="remarks" ></textarea>  
				</div>
				<div>
					<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
					<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
				</div>
			</div>
		</div>
	</div>
</form>
<script>
$('document').ready(function(){
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			leave_type: {
				validators: {
					notEmpty: {
						message: 'Please select type of leave.'
					}
				}
			},
			no_of_days: {
				validators: {
					notEmpty: {
						message: 'Please provide no of days.'
					},
					digits: {
						message: 'Please provide valid no of days.'
					},
				}
			},
			sanction_order_no: {
				validators: {
					notEmpty: {
						message: 'Please provide sanction order no.'
					}
				}
			},
			start_date: {
				validators: {
					notEmpty: {
						message: 'Please select start date.'
					}
				}
			},
			end_date:{
				validators: {
					notEmpty: {
						message: 'Please select end_date.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('#start_date').on('changeDate',function(){
			$('form').formValidation('revalidateField','start_date');
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField','end_date');
	});
});
</script>
