<?php
/**
 * 
 * View -- of Hr/EmployeeController/editqualificationAction
 * 
 */
?>
<?php 
    foreach($this->qualification as $qual):
        extract($qual);        
    endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('employee', array('action' => 'editqualification', 'id' => $this->id)); ?>"  enctype="multipart/form-data" >    
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Qualification</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label for="qualification" class="control-label">Qualification</label>
					<select class="form-control" name="qualification" id="qualification" data-placeholder="Select" required > 
						<option value=""></option>
						<?php foreach($q_levels as $q_level):
								$selected = ($q_level['id'] == $qualification)?'selected':'';?>
							<option value="<?php echo $q_level['id'];?>" <?php echo $selected;?>>
								<?php echo $q_level['qualification_level'];?></option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label for="course" class="control-label">Course</label>
					<input type="text" class="form-control" name="course" id="course" value="<?php echo $course;?>" required> 
				</div>
				<div class="form-group">
					<label for="institute" class="control-label">Institute</label>
					<input type="text" class="form-control" name="institute" id="institute" value="<?php echo $institute;?>" required> 
				</div>
				<div class="form-group">
					<label for="location" class="control-label">Location</label>
					<input type="text" class="form-control" name="location" id="location" value="<?php echo $location;?>" required> 
				</div>
				<div class="form-group">
					<label for="completion_year" class="control-label">Completion Year</label>
					<input type="text" class="form-control" name="completion_year" id="completion_year" value="<?php echo $completion_year;?>" required> 
					<input type="hidden" name="employee" id="employee" value="<?php echo $employee_id;?>"> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>  
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			qualification: {
				validators: {
					notEmpty: {
						message: 'Please provide qualification.'
					},
				}
			},
			institute: {
				validators: {
					notEmpty: {
						message: 'Please provide institute.'
					}
				}
			},
			location: {
				validators: {
					notEmpty: {
						message: 'Please provide location.'
					}	
				}
			},
			course: {
				validators: {
					notEmpty: {
						message: 'Please provide course.'
					}
				}
			},
			completion_year: {
				validators: {
					notEmpty: {
						message: 'Please provide completion year.'
					},
					digits: {
						message: 'Please provide valid completion year.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>  

