<?php
/**
 * 
 * View -- of Hr/EmployeeController/indexAction
 * 
 */
	$this->headTitle($this->title);
?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
			<form method="post" action="<?php echo $this->url('employee', array('action' => 'index')); ?>" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="emp_status">Department</label>
					<select class="form-control" id="department" name="department" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['department'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($this->department->getAll() as $departments):
							$sel_dept = ($departments['id'] == $data['department'])?'selected':'';
						?>
						<option value="<?php echo $departments['id'];?>" <?php echo $sel_dept;?>>
							<?php echo $departments['department'];?>
						</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="activity">Division</label>
					<select class="form-control" id="activity" name="activity" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['activity'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($this->division->get(array('department'=>$data['department'])) as $divisions):
							$sel_div = ($divisions['id'] == $data['activity'])?'selected':'';
						?>
						<option value="<?php echo $divisions['id'];?>" <?php echo $sel_div;?>>
							<?php echo $divisions['activity'];?>
						</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="section">Section</label>
					<select class="form-control" id="section" name="section" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['section'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($this->section->get(array('division'=>$data['activity'])) as $sections):
							$sel_sec = ($sections['id'] == $data['section'])?'selected':'';
						?>
						<option value="<?php echo $sections['id'];?>" <?php echo $sel_sec;?>>
							<?php echo $sections['section'];?>
						</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="emp_status">Employee Status</label>
					<select class="form-control" id="emp_status" name="emp_status" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['status'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($employee_status as $emp_status):
							$sel_status = ($emp_status['id'] == $data['status'])?'selected':'';
						?>
						<option value="<?php echo $emp_status['id'];?>" <?php echo $sel_status;?>>
							<?php echo $emp_status['status'];?>
						</option>
						<?php endforeach;?>
					</select>
				</div>
			</form>
			</div>
		</div>
		
			<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
			<a class ="btn btn-sm btn-info" href ="<?php echo $this->url('employee',array('action'=>'updateleavebalance'))?>">Update Leave Balance</a>
	</div>
		</div>
		</div>
		<div>
			<table class="table table-striped table-hover table-condensed" style="width:100%;" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Employee_id</th>
						<th>CID</th>
						<th>Department</th>
						<th>Location</th>
						<th>Position Title</th>
						<th>Category</th>
						<th>Status</th>
						<?php if($this->button(1)!=""):?>
						<th class='no-sort'>Action</th>
						<?php endif;?>
					</tr>
				</thead>
				<tbody>
					<?php $j = 1; foreach ($this->employee->getEmployeeBy($data) as $rows):?>
						<tr data-href="<?php echo $this->button(4, $rows['id']); ?>">
							<td><?php echo $j++; ?> </td>
							<td><b><?php echo $rows['full_name']; ?></b></td>
							<td><?php echo $rows['emp_id']; ?></td>
							<td><?php echo $rows['cid']; ?></td>
							<td><?php echo $this->department->getColumn($rows['department'],'department'); ?></td>
							<td><?php echo $rows['location']; ?></td>
							<td><?php echo $this->ptitle->getColumn($rows['position_title'],'position_title'); ?></td>
							<td><strong><?php echo $rows['type_code']; ?></strong> (<?php echo $rows['type']; ?>)</td>
							<td>
								<span class="label label-sm label-<?php echo $rows['status_color'];?>"><?php echo $rows['status'];?></span>
							</td>
						<?php if($this->button(1)!=""):?>
								<td><?php //echo $this->button(1,$rows['id'],$rows['system_user']);?><?php echo $this->button(1,$rows['id']);?></td>
							<?php endif;?>
						</tr>
					<?php 
					endforeach;  
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>

