<?php
/**
 * 
 * View -- of Hr/EmployeeController/addfamilyAction
 * 
 */
 foreach($employee as $emp);
?>

<form id="#form" method="post" action="<?php echo $this->url('employee', array('action' => 'updateindividualleave', 'id' => $id)); ?>"  enctype="multipart/form-data" >    
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i>Update Leave Opening</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label>Date:</label>
					<div class="date input-group" id="leave_balance_date" data-date-format="yyyy-mm-dd">
						<input class="form-control" name="leave_balance_date" id="leave_balance_date" type="text" placeholder="leave balance date" value="<?php echo $emp['leave_balance_date'];?>">
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div> 	
				<div class="form-group">
					<label for="leave_balance" class="control-label">Leave Balance</label>
					<input type="text" class="form-control" name="leave_balance" id="leave_balance" value="<?php echo $emp['leave_balance'];?>"  /> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form> 
<script>
$('document').ready(function(){
	$('#leave_balance_date').datepicker();
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			leave_balance_date: {
				validators: {
					notEmpty: {
						message: 'Please provide name.'
					}
				}
			},
			leave_balance: {
				validators: {
					notEmpty: {
						message: 'Please provide leave balance.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>  
