<?php
/**
 * 
 * View -- of Humanresource/EmployeeController/viewfamilyAction
 * 
 */
    $this->headTitle($this->title);
?>

<?php 
    foreach ($employee as $emp):
            extract($emp);
    endforeach;        
?>
<?php echo $this->partial('hr/employee/partial.phtml', array('active' => 'viewfamily', 'id' => $id)); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2,$id);?>
		</div>
	</div>
	<div class="table-responsive">
		<div class="table-header col-lg-4"> Family detail's of <?php echo $full_name; ?> </div>
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Relation</th>
					<th>Occupation</th>
					<th>Address</th>
					<th>Remarks</th>
					<th class="no-sort">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->family as $rows):
				?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<td><?php echo $rows['name']; ?></td>
						<td><?php echo $rows['relation']; ?></td>
						<td><?php echo $rows['occupation']; ?></td>
						<td><?php echo $rows['address']; ?></td>
						<td><?php echo $rows['remarks']; ?></td>
						<?php if($this->button(1)!=""):?>
							<td><?php echo $this->button(1,$rows['id']);?></td>
						<?php endif;?>						
					</tr>
				<?php 
				endforeach;  
				?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>
