<?php
/**
 * 
 * View -- of Hr/EmployeeController/viewqualificationAction
 * 
 */
    $this->headTitle($this->title);
?>

<?php 
    foreach ($employee as $emp):
            extract($emp);
    endforeach;        
?>
<?php echo $this->partial('hr/employee/partial.phtml', array('active' => 'viewqualification', 'id' => $id)); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2,$id);?>
		</div>
	</div>
	<div class="table-responsive">
		<div class="table-header col-lg-4"> Qualification detail's of <?php echo $full_name; ?> </div>
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Qualification</th>
					<th>Course</th>
					<th>Institute</th>
					<th>Location</th>
					<th>Completion Year</th>
					<th class="no-sort no-print">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->qualification as $rows):
				?>
					<tr>
						<td><?php echo $i; ?> </td>
						<td><?php echo $this->q_levelsObj->getColumn($rows['qualification'],'qualification_level'); ?></td>
						<td><?php echo $rows['course']; ?></td>
						<td><?php echo $rows['institute']; ?></td>
						<td><?php echo $rows['location']; ?></td>
						<td><?php echo $rows['completion_year']; ?></td>
							<?php if($this->button(1)!=""):?>
							<td><?php echo $this->button(1,$rows['id']);?></td>
						<?php endif;?>			
					</tr>
				<?php 
				$i++;
				endforeach;  
				?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>

