<?php
/**
 * View -- of Administration/MasterController/addregion
 * chophel@athang.com
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('setmaster', array('action' => 'addregion','id'=>$page)); ?>" enctype="multipart/form-data">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
    </div><!-- /modal-header -->
    <div class="modal-body">        
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="form-group">
					<label for="department" class="control-label">Department</label>
					<select class="form-control" name="department" placeholder="department" >
						<option value=""></option>
						<?php foreach($department as $dep):?>
							<option value="<?php echo $dep['id'];?>"><?php echo $dep['department'];?>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label for="region" class="control-label">Region</label>
					<input class="form-control" name="region" placeholder="Region" required >
				</div>
				<div  class="form-group">
					<label for="status" class="control-label">Status</label>
					<div class="radio">
						<label>
							<input class="ace" type="radio" name="status" id="status" value="1" checked />
							<span class="lbl"> Yes </span>
						</label>
						<label>
							<input class="ace" type="radio" name="status" id="status" value="0" />
							<span class="lbl"> No </span>
						</label>
					</div>
				</div>
			</div>
		</div>      
    </div><!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div><!-- /modal-footer -->
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			region: {
				validators: {
					notEmpty: {
						message: 'Please provide region.'
					}
				}
			},	
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},		
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	});
</script>