<?php
/**
 * View -- of Administration/MasterController/editactivity
 * chophel@athang.com
 */
?>
<?php foreach($activities as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('setmaster', array('action' => 'editactivity','id'=>$page)); ?>" enctype="multipart/form-data">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="ace-icon fa fa-pencil-square-o"></i> <?php echo $this->title; ?></h4>
    </div>  <!-- /modal-header -->    
    <div class="modal-body">  
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label for="department" class="control-label">Department</label>
					<select id="department" name="department" class="form-control" data-placeholder="Select" required>
						<option value=""></option>
						<?php foreach($departments as $department):?>
							<option value="<?php echo $department['id'];?>" <?php echo ($row['id']==$department['id'])?"selected":"";?>>
								<?php echo $department['department']; ?></option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label for="activity" class="control-label">Activity Name</label>
					<input type="text" class="form-control" name="activity" id="activity" value="<?php echo $row['activity'];?>" size="30" required /> 
				</div>
				<div class="form-group">
					<label for="prefix" class="control-label">Prefix</label>
					<input type="text" class="form-control" name="prefix" id="prefix" value="<?php echo $row['prefix'];?>" size="30" placeholder='Activity Prefix' required> 
				</div>
				<div class="form-group">
					<label for="status" class="control-label">Status</label>
					<div class="radio">
						<label>
							<input class="ace" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
							<span class="lbl"> Yes </span>
						</label>
						<label>
							<input class="ace" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
							<span class="lbl"> No </span>
						</label>
					</div>
				</div> 
			</div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			department: {
				validators: {
					notEmpty: {
						message: 'Please select Department.'
					}
				}
			},
			activity: {
				validators: {
					notEmpty: {
						message: 'Please provide Activity.'
					}
				}
			},
			prefix: {
				validators: {
					notEmpty: {
						message: 'Please provide Activity Prefix.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>