 <?php
/**
 * View -- of Administration/MasterController/editlocationtypeAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php foreach ($locationtypes as $row);?> 
<form id="#form" action="<?php echo $this->url('setmaster', array('action' => 'editlocationtype', 'id' => $page));?>" method="post" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"> <i class="ace-icon fa fa-pencil-square-o"></i> <?php echo $this->title; ?></h4>
    </div> <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row"> 
					<input type="hidden" id="locationtype_id" name="locationtype_id" value="<?php echo $row['id'];?>" />
					<div  class="form-group col-lg-12">
						<label for="location_type" class="control-label">Location Type</label>
						<input class="form-control" value="<?php echo $row['location_type'];?>" type="text" name="location_type" id="location_type" placeholder="Location Type" required />
					</div>
					<div  class="form-group col-lg-12">
						<label for="description" class="control-label">Description</label>
						<input class="form-control" value="<?php echo $row['description'];?>" type="text" name="description" id="description" placeholder="Description" required />
					</div>
				
					<div  class="form-group col-lg-6">
						<label for="sales" class="control-label">Sales</label>
						<div class="radio">
							<label>
								<input class="ace" type="radio" name="sales" id="sales" value="1" <?php echo ($row['sales']=='1')?"checked":"";?> />
								<span class="lbl"> Yes </span>
							</label>
							<label>
								<input class="ace" type="radio" name="sales" id="sales" value="0" <?php echo ($row['sales']=='0')?"checked":"";?> />
								<span class="lbl"> No </span>
							</label>
						</div>
					</div>
					<div  class="form-group col-lg-6">
						<label for="status" class="control-label">Status</label>
						<div class="radio">
							<label>
								<input class="ace" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
								<span class="lbl"> Yes </span>
							</label>
							<label>
								<input class="ace" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
								<span class="lbl"> No </span>
							</label>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>  
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			location_type: {
				validators: {
					notEmpty: {
						message: 'Please provide PIU type.'
					}
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide description.'
					}
				}
			},
			sales: {
				validators: {
					notEmpty: {
						message: 'Please select if there is sales.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>