<?php
/**
 * View -- of Administration/MasterController/addactivity
 * chophel@athang.com
 */
?>
<?php foreach($activities as $row);
?>
<form id="#form" method="post" action="<?php echo $this->url('setmaster', array('action' => 'editsection','id'=>$page)); ?>" enctype="multipart/form-data">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
    </div>     
    <div class="modal-body">    
	<input type="hidden"  name="section_id"  value="<?php echo $row['id'];?>"> 
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label for="division" class="control-label">Division</label>
						<select id="division" name="division" class="form-control" data-placeholder="Select" required>
						<option value=""></option>
						<?php foreach($division as $divisions):?>
							<option value="<?php echo $divisions['id'];?>" <?php echo ($row['id']==$divisions['id'])?"selected":"";?>>
								<?php echo $divisions['activity']; ?></option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label for="section" class="control-label">Section</label>
					<input type="text" class="form-control" name="section" id="section" value="<?php echo $row['section'];?>" placeholder='Section' required> 
				</div> 
				<div class="form-group">
					<label for="prefix" class="control-label">Prefix</label>
					<input type="text" class="form-control" name="prefix" id="prefix" value="<?php echo $row['prefix'];?>" size="30" placeholder='Activity Prefix' required> 
				</div> 
				<div class="radio">
						<label>
							<input class="ace" type="radio" name="status" id="status" value="1" <?php echo ($row['status']=='1')?"checked":"";?> />
							<span class="lbl"> Yes </span>
						</label>
						<label>
							<input class="ace" type="radio" name="status" id="status" value="0" <?php echo ($row['status']=='0')?"checked":"";?> />
							<span class="lbl"> No </span>
						</label>
					</div>
            </div>
        </div>
    </div>    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>  
