<?php
/**
 * View -- of Administration/DomainController/locationAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(422,425,428,431,434,437)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-9">
				<form method="POST" action="<?php echo $this->url('setmaster', array('action' => 'location','id'=>$page)); ?>" enctype="multipart/form-data" >    
					<div class="row">
						<div class="form-group col-lg-4">
							<label for="region" class="control-label">Region</label>
							<select id="region" name="region" class="form-control" data-placeholder="Select" onchange='this.form.submit()' >
								<option value="-1" <?php echo ($data['region'] == '-1')?'selected':'';?>>All</option>
								<?php foreach($this->regionObj->get(array('status'=>'1')) as $region):?>
									<option value="<?php echo $region['id']?>"<?php echo ($region['id']==$data['region'])?'selected':'';?>>
										<?php echo $region['region'];?></option>
								<?php endforeach;?>
							</select>
						</div>
						<div class="form-group col-lg-4">
							<label for="location_type" class="control-label">Location Type</label>
							<select id="location_type" name="location_type" class="form-control" data-placeholder="Select" onchange='this.form.submit()' >
								<option value="-1" <?php echo ($data['location_type'] == '-1')?'selected':'';?>>All</option>
								<?php foreach($this->locationtypeObj->get(array('status'=>'1')) as $locationtype):?>
									<option value="<?php echo $locationtype['id']?>"<?php echo ($locationtype['id']==$data['location_type'])?'selected':'';?>>
										<?php echo $locationtype['location_type'];?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>
			<div class="col-lg-3 ">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2,$page);?>
				</div>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Location</th>
					<th>Location Type</th>
					<th>Code</th>
					<th>Region</th>
					<th>District</th>
					<th>Status</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php 
				$i=1;
				foreach ($paginator as $row):?>
				<tr>
					<td><?php  echo $i++; ?></td>								       
					<td class="fw-bold"><?php echo $row['location']; ?></td>
					<td><?php echo $this->locationtypeObj->getColumn($row['location_type'],'location_type'); ?></td>
					<td><?php echo $row['location_code'];?></td>
					<td><?php echo ($row['region']!='0')?$this->regionObj->getColumn($row['region'],'region'):'-'; ?></td>
					<td><?php echo ($row['district']!='0')?$this->districtObj->getColumn($row['district'],'district'):'-'; ?></td>
					<td><?php echo $this->status($row['status']); ?></td>
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
			array('route' => 'setmaster/paginator','action'=>'location','id'=>$data['region']."_".$data['location_type']));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#dataTables').DataTable();
});
</script>