<?php 
/**
 * View -- of Acl/LogsController/loginlogAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(252,253)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-6">
				<form method="POST" class="form-horizontal">
					<div class="form-group row">
						<label class="control-label col-sm-4">User</label>
						<div class="col-sm-8">
							<select id="user" name="user" class="form-control" data-placeholder="Select">
								<?php foreach($this->userObj->getAll(array('location_permit'=>'-1','activity_permit'=>'-1','status_permit'=>'-1','onlyifcreator_permit'=>'-1')) as $user):?>
								<?php $selected = ($user['id']==$this->resource)?'selected':'';?>
									<option value="<?php echo $user['id']?>"<?php echo $selected;?>><?php echo $user['name']." (".$user['email'].")";?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>User</th>
					<th>Role</th>
					<th>Process</th>
					<th>ProcessID</th>
					<th>Status</th>
					<th>remarks</th>
					<th>Timestamp</th>
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach ($paginator as $row):?>
				<tr>
					<td><?php echo $i++;?></td>
					<td><?php echo $this->userObj->getColumn($row['author'],'name'); ?></td>				   
					<td><?php echo $this->roleObj->getColumn($row['role'],'role'); ?></td>
					<td><?php echo $this->processObj->getColumn($row['process'],'process'); ?></td>	
					<td><?php echo $row['process_id']; ?></td>	
					<td><?php echo $this->status($row['status']); ?></td>
					<td><?php echo $row['remarks']; ?></td>	
					<td><?php echo $row['created']; ?></td>	
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','acl_pagination.phtml', 
			array('route' => 'logs/paginator','action'=>'audit','id'=>$this->resource,'role'=>'0','task'=>'0'));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#user').change(function(){
		window.location.href="<?php echo $this->url('logs',array('action'=>'audit'));?>/"+$(this).val();
	});
	$('#dataTables').DataTable();
});
</script>