<?php 
/**
 * View -- of Acl/AclController/addrolelist
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('acl', array('action' => 'addrolelist','id'=>$page)); ?>" enctype="multipart/form-data">                  
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body"> 
        <div class="panel panel-default">
			<div class="panel-body">  
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="control-label">Role</label>
                            <input type="text" class="form-control" name="role" id="role" placeholder='Role' required />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Description</label>
                            <input type="text" class="form-control" name="description" id="description" placeholder='Description' required />
                        </div>
                        <div  class="form-group">
                            <label for="status" class="control-label">Status</label>
                            <div class="radio">
                                <label>
                                    <input class="ace" type="radio" name="status" id="status" value="1" checked />
                                    <span class="lbl"> Yes </span>
                                </label>
                                <label>
                                    <input class="ace" type="radio" name="status" id="status" value="0" />
                                    <span class="lbl"> No </span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
		    </div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
<script>
    FormValidation.formValidation(document.getElementById('#form'), {
        fields: {
            role: {
                validators: {
                    notEmpty: {
                        message: 'Please provide role name.'
                    }
                }
            },
            description: {
                validators: {
                    notEmpty: {
                        message: 'Please provide description.'
                    }
                }
            },
            status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
        },
        plugins: {
            trigger: new FormValidation.plugins.Trigger(),
            bootstrap3: new FormValidation.plugins.Bootstrap3(),
            submitButton: new FormValidation.plugins.SubmitButton(),
            defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
        },
    });
</script>