<?php 
/**
 * View -- of Acl/AclController/transferpermission
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>

<form id="#form" method="post" action="<?php echo $this->url('acl', array('action' => 'transferpermission','id'=>$data['selected_data'])); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="ace-icon fa fa-exchange"></i><?php echo $this->title; ?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body"> 
		<div class="panel panel-default">
			<div class="panel-body">  
				<div class="row">
					<div class="form-group col-lg-12">  
						<label for="module" class="control-label">Module</label>
						<select id="module" name="module" class="form-control" data-placeholder="Select" disabled>
							<option value="-1" <?php echo ($data['resource']=='-1')?'selected':'';?>>Select Module</option>
							<?php foreach($modules as $module):?>
								<option value="<?php echo $module['id']?>" <?php echo ($data['resource']==$module['id'])?'selected':'';?>>
									<?php echo $module['module'];?></option>
							<?php endforeach;?>
						</select>
					</div>
				</div>
				<div class="row">
					<div class="form-group col-lg-12">
						<label for="process" class="control-label">Process</label>
						<select id="process" name="process" class="form-control" data-placeholder="Select" disabled>
							<option value=""></option>
							<?php if($data['resource']!='-1'):foreach($this->processObj->get(array('resource'=>$data['resource'])) as $process):?>
								<option value="<?php echo $process['id']?>" <?php echo ($data['process']==$process['id'])?'selected':'';?>>
									<?php echo $process['process'];?></option>
							<?php endforeach;endif;?>
						</select>
					</div>
				</div>
				<div class="row">
					<div class="form-group col-lg-12">
						<label for="role" class="control-label">Role</label>
						<select id="role" name="role" class="form-control" data-placeholder="Select" disabled>
							<option value=""></option>
							<?php foreach($this->roleObj->getAllExcept('100') as $role):?>
								<option value="<?php echo $role['id']?>" <?php echo ($data['role']==$role['id'])?'selected':'';?>>
									<?php echo $role['role'];?></option>
							<?php endforeach;?>
						</select>
					</div>
				</div>
				<div class="row">
					<div class="form-group col-lg-12">
						<label for="transfer_to_role" class="control-label">Transfer To Role</label>
						<select id="transfer_to_role" name="transfer_to_role" class="form-control" data-placeholder="Select">
							<option value=""></option>
							<?php foreach($this->roleObj->getAllExcept('100') as $transferrole):?>
								<option value="<?php echo $transferrole['id']?>" <?php echo ($data['role']==$transferrole['id'])?'selected':'';?>>
									<?php echo $transferrole['role'];?></option>
							<?php endforeach;?>
						</select>
					</div>
				</div>
				<input type="hidden" name="module_id" id="module_id" value="<?php echo $data['resource'];?>" />
				<input type="hidden" name="process_id" id="process_id" value="<?php echo $data['process'];?>" />
				<input type="hidden" name="role_id" id="role_id" value="<?php echo $data['role'];?>" />
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
	$('select#module').on('change',function(){
		$('input#module_id').val($(this).val());
	});
	$('select#process').on('change',function(){
		$('input#process_id').val($(this).val());
	});
	$('select#role').on('change',function(){
		$('input#role_id').val($(this).val());
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			module: {
				validators: {
					notEmpty: {
						message: 'Please select module.'
					}
				}
			},
			process: {
				validators: {
					notEmpty: {
						message: 'Please select process.'
					}
				}
			},
			role: {
				validators: {
					notEmpty: {
						message: 'Please select role.'
					}
				}
			},
			transfer_to_role: {
				validators: {
					notEmpty: {
						message: 'Please select transfer to role.'
					}
				}
			},
		},plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>

