<?php
/**
 * 
 * View -- of Hr/PayrollController/addearningAction
 * 
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('payroll', array('action' => 'addrevenueno', 'id'=>$this->year.'-'.$this->month)); ?>"  enctype="multipart/form-data" >    
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> 
       		Add Revenue Number
        </h4>
    </div>     
    <div class="modal-body">    
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label for="revenue_no" class="control-label">Revenue Number </label>
					<input type="text" class="form-control" name="revenue_no" id="revenue_no"  /> 
				</div>	
				
            </div>
        </div>
    </div>    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form> 
