<?php // partial.phtml 
	$payroll = ($this->active == "payroll")?"active":"";
	$pepf = ($this->active == "pepf")?"active":"";
?>
<br/>
<ul class="nav nav-tabs padding-18" id="myTab">	
	<li class="<?php echo $payroll; ?>">
		<a href="<?php echo $this->url('payroll', array('action' => 'index')); ?>" title="Payroll">
			<i class="blue ace-icon fa fa-bar-chart bigger-120"></i>
			<span class="hidden-xs">Generate Payroll</span>
		</a>
	</li>
	<li class="<?php echo $pepf; ?>">
		<a href="<?php echo $this->url('payroll', array('action' => 'pepf')); ?>" title="PE PF">
			<i class="red ace-icon fa fa-file-text bigger-120"></i>
			<span class="hidden-xs">Generate PE PF</span>
		</a>
	</li>
</ul>


