<?php 
/**
 * View -- of Implementation/ImplementationController/confirmimplementationAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php foreach($pbvi as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('payroll', array('action' => 'submitpbvi')); ?>" enctype="multipart/form-data">                 
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-checked"></i> Submit PBVI for the Period <?php echo $row['year']?></h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">
              <input type="hidden" value="<?php echo $row['id'];?>" name="id" id="id"/>			
		        <div class="alert alert-primary">
			    <div class="row">	
                    <div class="form-group">
                        <label for="date" class="control-label">Submition Date</label>
                        <div class="date input-group" id="date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
                            <input class="form-control span2" name="date" id="date" type="text" placeholder="Date" value="<?php echo date('Y-m-d');?>" readonly required>
                            <span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="remarks" class="control-label">Remarks</label>
                        <textarea class="form-control" name="remarks" rows="2" placeholder="Remarks..." required></textarea>
                    </div>
                </div>
		        </div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-checkbox"></i> Submit </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>  
<script>
	$('document').ready(function(){
		$('#date').datepicker();
	});
</script>