<?php 
/**
 * View -- of Implementation/ImplementationController/confirmimplementationAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('user', array('action' => 'late','id'=>$id)); ?>" enctype="multipart/form-data">                 
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-checked"></i>Reason FOr coming late</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">
              <div class="form-group">
			<label for="reason" class="control-label">Reasons</label>
			<textarea class="form-control" rows="3" name="reason" required>
			</textarea>
		</div>		

			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-checkbox"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>  