<?php 
/**
 * View -- of Implementation/ImplementationController/confirmimplementationAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
	foreach($timing as $timings);
?>
<form id="#form" method="post" action="<?php echo $this->url('user', array('action' => 'timing','id'=>$timings['id'])); ?>" enctype="multipart/form-data">                 
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-edit"></i>Update Timing</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label for="leave" class="control-label">Time for leaving office</label>
					<input class="form-control" type="text" name="leave" id="leave" value="<?php echo $timings['leave'];?>">
				</div>
				<div class="form-group">
					<label for="remarks" class="control-label">Remarks</label>
					<input class="form-control" type="text" name="remarks" id="remarks" value="<?php echo $timings['remarks'];?>">
				</div>		

			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="icon ti ti-checkbox"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>  