<?php 
/**
 * View -- of Administration/UserController/useractivityAction
 * chophel@athang.com 
 */
	$this->headTitle($this->title);
?>
<?php foreach ($users as $user);?>
<?php echo $this->tabs_helper(array(403,409,410),$user['id']); ?>
<div class="card">
	<div class="card-header"></div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Timestamp</th>
					<th>Process</th>
					<th>Status</th>
					<th>Remarks</th>          
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*25); foreach($paginator as $row):?>
			<tr>
				<td><?php echo $i++; ?></td>
				<td><?php echo $row['created']; ?></td>
				<td><?php echo $this->processObj->getColumn($row['process'],'process'); ?></td>
				<td><?php echo $this->status($row['status']);?></td>
				<td><?php echo $row['remarks'];?></td>
			</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
			array('route' => 'user/paginator','action'=>'useractivity','id'=>$user['id']));?>
	</div>
</div>
<script type="text/javascript">
	$('#dataTables').DataTable();
</script>