<?php
/**
 * View -- of Administration/FlowController/addflow
 * chophel@athang.com
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('flow', array('action' => 'addflow','id'=>$page)); ?>" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">  
				<div class="row"> 
					<div class="col-lg-12"> 
						<div  class="form-group">
							<label for="flow" class="control-label">Work Flow Name</label>
							<input class="form-control" type="text" name="flow" id="flow" placeholder="Work Flow Name" required />
						</div>
						<div class="form-group">  
							<label class="control-label" for="process">Process</label>
							<select id="process" name="process" class="form-control" data-placeholder="Select">
								<option value=""></option>
								<?php foreach($processes as $process):?>
									<option value="<?php echo $process['id']?>">
										<?php echo $process['process'];?></option>
								<?php endforeach;?>
							</select>
						</div>
						<div class="form-group">  
							<label class="control-label" for="role">Role</label>
							<select id="role" name="role" class="form-control" data-placeholder="Select">
								<option value=""></option>
								<?php foreach($roles as $role):?>
									<option value="<?php echo $role['id']?>">
										<?php echo $role['role'];?></option>
								<?php endforeach;?>
							</select>
						</div>
						<div  class="form-group">
							<label for="description" class="control-label">Description</label>
							<textarea class="form-control" type="text" name="description" id="description"></textarea>
						</div>
						<div  class="form-group">
							<label for="status" class="control-label">Status</label>
							<div class="radio">
								<label>
									<input class="ace" type="radio" name="status" id="status" value="1" checked />
									<span class="lbl"> Yes </span>
								</label>
								<label>
									<input class="ace" type="radio" name="status" id="status" value="0" />
									<span class="lbl"> No </span>
								</label>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			flow: {
				validators: {
					notEmpty: {
						message: 'Please provide work flow name.'
					}
				}
			},
			process: {
				validators: {
					notEmpty: {
						message: 'Please select process.'
					}
				}
			},
			role: {
				validators: {
					notEmpty: {
						message: 'Please select role.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>