<?php
/**
 * View -- of Administration/FlowController/flowactionAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(482,489)); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2,$page);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-wrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Action</th>
					<th>Description</th>
					<th>UI Class</th>
					<th>UI Icon</th>
					<th>Status</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach ($paginator as $row):?>
				<tr>
					<td><?php  echo $i++; ?></td>								       
					<td class="fw-bold"><?php echo $row['action']; ?></td>
					<td><?php echo $row['description']; ?></td>
					<td><?php echo $row['class']; ?></td>
					<td><i class="ace-icon <?php echo $row['icon'];?>"></i></td>
					<td><?php echo $this->status($row['status']); ?></td>
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
			array('route' => 'flow/paginator','action'=>'flowaction','id'=>0));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#district').change(function(){
		window.location.href="<?php echo $this->url('setmaster',array('action'=>'block'));?>/"+$(this).val();
	});
	$('#dataTables').DataTable();
});
</script>