 <?php
/**
 * View -- of Administration/FlowController/removeflowprivilegeAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php foreach ($privileges as $row);?> 
<form id="#form" action="<?php echo $this->url('flow', array('action' => 'removeflowprivilege', 'id' => $page));?>" method="post" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"> <i class="ace-icon fa fa-trash-o"></i> <?php echo $this->title; ?></h4>
    </div> <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">  
				<div class="row"> 
					<div class="col-lg-12"> 
						<input type="hidden" id="privilege_id" name="privilege_id" value="<?php echo $row['id'];?>" />
						<input type="hidden" id="flow_id" name="flow_id" value="<?php echo $row['flow'];?>" />
						<div class="row col-lg-12">
							<div class="alert alert-warning"> 
								<b><WARNING</b> Are you sure you want to remove the following privilege from the work flow?<br>
							</div>
						</div>
						<table class="table table-bordered">
							<tbody>
								<tr>
									<th><u>Status Changed To:</u></th>
									<td><?php echo $this->status($row['status_changed_to']); ?></td>
								</tr>
								<tr>
									<th><u>Route To Role</u></th>
									<td><?php echo ($row['route_to_role']=='0')?'-':$this->roleObj->getColumn($row['route_to_role'],'role');?></td>
								</tr>
								<tr>
									<th>Actions</th>
									<td><?php $btn_array = explode("|", $row['action']);
										for($j=0;$j<sizeof($btn_array);$j++):
											echo '"'.$this->actionObj->getColumn($btn_array[$j],'action').'"';
											echo ($j != sizeof($btn_array)-1)?" | ":"";
										endfor;
									?></td>								
								</tr>
								<tr>
									<th>Description</th>
									<td><?php echo $row['description']; ?></td>								
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-trash-o"></i>Remove</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button>
    </div>  
</form>