<?php
/**
 * Authentication --- login
 * chophel@athang.com
 */
	$this->headTitle($title);
?> 
<div class="row">
	<div class="col-sm-10 col-sm-offset-1">
		<div class="login-container">
			<div class="center">
				<h1>
					<img style="height:100px"src="<?php echo $this->basePath() . '/images/logo.png' ?> "/>
				</h1>
				<h3 class="blue" id="id-company-text">
					&copy;<span class="red"> Bhutan Post</span><span id="id-text2"> ERP-System</span>
				</h3>
			</div>
			<div class="space-6"></div>
			<div class="position-relative">
				<div id="forgot-box" class="forgot-box visible widget-box no-border">
					<div class="widget-body">
						<div class="widget-main">
							<h4 class="header red lighter bigger">
								<i class="ace-icon fa fa-key"></i>Retrieve Password
							</h4>
							<div class="space-6"></div>
							<p>Enter your email to receive instructions</p>
							<form id="#form" method="post" action="<?php echo $this->url('auth', array('action' => 'forgotpwd')); ?>">
								<fieldset>
									<div class="form-group">
										<span class="block input-icon input-icon-right">
											<input type="email" class="form-control" name="email" placeholder="Email" />
											<i class="ace-icon fa fa-envelope"></i>
										</span>
									</div>
									<div class="form-group">
										<style> pre{font-size: 10px; line-height:1.4;} </style>
										<?php echo $this->FormLabel($captcha->get('captcha')); ?>
										<?php echo $this->FormElement($captcha->get('captcha')); ?>		
									</div>
									<div class="clearfix">
										<button type="submit" class="width-35 pull-right btn btn-sm btn-danger">
											<i class="ace-icon fa fa-lightbulb-o"></i>
											<span class="bigger-110">Send Me</span>
										</button>
									</div>
								</fieldset>
							</form>
						</div><!-- /.widget-main -->
						<div class="toolbar center">
							<a href="<?php echo $this->url('auth', array('action' => 'login')); ?>" data-target="#login-box" class="back-to-login-link">
								Back to login
								<i class="ace-icon fa fa-arrow-right"></i>
							</a>
						</div>
					</div><!-- /.widget-body -->
				</div><!-- /.forgot-box -->
			</div><!-- /.position-relative -->
		</div>
	</div><!-- /.col -->
</div><!-- /.row -->
<script>
	document.addEventListener('DOMContentLoaded', function (e) {
		FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				email: {
					validators: {
						notEmpty: {
							message: 'Please provide email address'
						},
						emailAddress: {
	                        message: 'Please provide valid email address'
	                    }
					}
				},
				'captcha[input]':{
					selector: '.captcha',
					validators: {
						notEmpty: {
							message: 'Please enter the generated captcha-figlet as shown above.'
						},
					}
				}
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		});
	});
</script>