<?php
/**
 * 
 * View -- of Auth/UserController/indexAction
 * 
 */
    $this->headTitle($this->title);    
?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12">
            <h4>All Notifications</h4>
            <table class="table table-striped table-bordered table-hover" id="dataTables">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Notification</th>    
                        <th>Date</th>
                        <th>Notifier</th>                
                        <th>Message</th>                
                    </tr>
                </thead>
                      
                <tbody>
                    <?php
                        $i = 1; 
                        $allnotifications = $this->notifyObj->get(array('user' =>$this->userID));
                        foreach ($allnotifications as $row):
                            
                            if($row['flag']==0){ $trCalss = "success"; }else { $trCalss = ""; }
                    ?>
                        <tr class="<?php echo $trCalss; ?>">
                            <td><?php echo $i++; ?> </td>
                            <td><?php 
                            $notificationResult = $this->notificationsObj->get($row['notification']);
                            foreach($notificationResult as $notify); ?>
                            <a href="<?php echo $this->url($notify['route'], array('action'=>$notify['action'], 'id'=>$notify['key']));?>"><?php echo $notify['description'];?></a></td>        
                            <td> <?php $datetime =strtotime($row['created']);
                                    echo date("F j, Y, g:i a",$datetime);?>
                            </td>
                            <td><?php
                              echo $username = $this->userObj->getColumn($row['author'], $column="name");?>
                            </td>    
                            <td><?php
                              echo $row['desc'];?>
                            </td>                                
                        </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
            </div>
   </div>
    </div>
</div>
<script>	
 $('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
