<?php
/**
 * View -- of Application/IndexController/indexAction
 * chophel@athang.com
 */
	$this->headTitle($title);
?>
<div class="page-header">
	<h1>
		Dashboard
		<small>
			<i class="ace-icon fa fa-angle-double-right"></i>
			overview &amp; stats
		</small>
	</h1>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="alert alert-block alert-success">
			<button type="button" class="close" data-dismiss="alert">
				<i class="ace-icon fa fa-times"></i>
			</button>
			<i class="ace-icon fa fa-check green"></i>
			Welcome to
			<strong class="green">
				Monal-ERP
				<small> v1.0</small>
			</strong>,
			This is an Empty Page for Testing Purpose.
		</div>
	</div>
</div>