<?php
/**
 * View -- of Application/IndexController/panel1Action
 * chophel@athang.com
 */
	$this->headTitle($title);
?>
<div class="page-header">
    <div class ="row">
		<div class ="col-lg-6">
			<h1>Admin Dashboard</h1>
		</div>
		<div class ="col-lg-6 text-right">
			<a href="https://forms.gle/ZLL6K3Efe6D8gYE19" target="_blank" class="btn btn-primary btn-sm">
				Hall Booking
			</a>
		</div>
	</div>
</div><!-- /.page-header -->
<div class="row">
	<div class="col-lg-12">
		<div class="widget-box">
			<div class="widget-header widget-header-flat widget-header-small">
				<h5 class="widget-title">
					<i class="ace-icon fa fa-map"></i>Employees on Leave today(<?php echo date('d-m-Y')?>)
				</h5>
				<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Location</th>
						<th>Designation</th>
						<th>Leave Type</th>
						<th>From Date</th>
						<th>To Date</th>
						<th>Duration</th>
						<th>Officiating</th>
						<th>Status</th>
					</tr>
				</thead>
				<tbody>
				<?php
					$i = 1; $total=0;
					foreach ($paginator as $row):
					?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<?php foreach ($this->employeeObj->get(array('e.id'=>$row['employee'])) as $emp);?>
						<td><?php echo $emp['full_name'];?></td>	
						<td><?php echo $emp['location'];?></td>	
						<td><?php echo $emp['designation'];?></td>
						<td><?php echo $this->leaveObj->getColumn($row['leave_type'],'type');?></td>	
						<td><b><?php echo $row['start_date'];?></b></td>	
						<td><b><?php echo $row['end_date'];?></b></td>
						<td><b><?php echo $row['no_of_days'];?>&nbsp Days</b></td>						
						<td><?php if(empty($row['delegation'])):" ";else:echo $this->employeeObj->getColumn($row['delegation'],'full_name');endif;?></td>
						<td><?php echo $this->status($row['status']);?></td>	
					</tr><?php endforeach;?>
				</tbody>
			</div>
		</div><!-- /.widget-box -->
	</div><!-- /.col -->
	
</div><!-- /.row -->

<div class="row">
	<div class="col-lg-12">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			
	</div>
</div>
</div>
<hr>
<div class="row">
	<div class="col-lg-12">
		<?php foreach($this->menus as $menu):?>
			<div class="monal_dashboard_menu" >
				<div class="app_icon"  style="background-color:<?php echo $menu['color'];?>" data-url="<?php echo $this->url($menu['route']);?>" >
					<i class="<?php echo $menu['icon'];?> fa-3x"></i>
				</div>
				<div class="small">
					<?php echo $menu['menu'];?>
				</div>
			</div>
		<?php endforeach;?>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-sm-6">
		<div class="widget-box">
			<div class="widget-header widget-header-flat widget-header-small">
				<h5 class="widget-title">
					<i class="ace-icon fa fa-map"></i>Geo Reference
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<div id="map" class="leaflet-map"></div>
					<?php $districts = $this->districtObj->getAll();
						$locations = $this->locationObj->get(array('status'=>'1'));
						echo $this->leaflet('map', $districts, $locations, $this->basePath());?>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$('.app_icon').each(function(){
		$(this).bind('click',function(){
			location.href=$(this).attr('data-url');
		});
	});
</script>