<?php
/**
 * 
 * View -- of Hr/LeaveController/addencashmentAction
 * 
 */
$this->headTitle($this->title);
$checkleaveOfficial =$this->userObj->get(array('id'=>$this->userID, 'role'=>100));
?>
<form id="#form" method="post" action="<?php echo $this->url('leave', array('action' => 'addencashment')); ?>"  enctype="multipart/form-data" >
	<div class="row">
		<div class="col-lg-12"> 
			<div class="widget-box transparent">
				<div class="widget-header widget-header-smaller">
					<h4 class="widget-title blue bolder smaller"> Leave Encashment Form </h4>
				</div>
				<div class="widget-body">
					<div class="widget-main padding-24"> 
						<div class="row">  
						   <div class="form-group col-lg-4">
								<label for="start_date" class="control-label">Leave Encashment Date</label>
								<div class="date input-group" id="encash_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="encash_date" id="encash_date" type="text" value="<?php echo date('Y-m-d'); ?>"  required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
						   </div>
						   <div class="form-group col-lg-4">
								<label for="applicant" class="control-label">Applicant</label>
								<select class="form-control" id="applicant" name="applicant" data-placeholder="-Select-" required >
									<option value=""></option>									
									<?php 
									if(sizeof($checkleaveOfficial) > 0){
									  $employees = $this->employeeObj->get(array('e.status'=>array(1,4,5)));
									  foreach ($employees as $employee):
									   ?>
										 <option value="<?php echo $employee['id'];?>"><?php echo $employee['full_name'];?> (Emp No. : <?php echo $employee['emp_id'];?>)</option>
									   <?php
									  endforeach;
									}
									else{
									    $loginEmployee = $this->employeeObj->get($this->login_emp_ID);
										foreach($loginEmployee as $employee);
										?>
										  <option value="<?php echo $employee['id'];?>"><?php echo $employee['full_name'];?> (Emp No. : <?php echo $employee['emp_id'];?>)</option>
										<?php
									} ?>									
								</select>
							</div>
						</div>
						<div class="row">  
						   <div class="form-group col-lg-10" id="empdtl"></div>						   
						</div>
						<div class="row">
							<div class="col-lg-8  alert alert-info fade in">
								<div class="form-group col-lg-4">
									<label for="earned_bal" class="control-label">Earned Leave(Day/s) Balance</label>
									<input type="text" class="form-control" id="earned_bal" name="earned_bal" readonly required>
								</div>
							<div class="form-group col-lg-4">
								<label for="no_of_days" class="control-label">No. of Days to Encash</label>
								<input type="text" class="form-control" name="no_of_encashed_days" id="no_of_encashed_days" value="30" readonly required> 
							</div>
							<div class="form-group col-lg-4">
								<label for="no_of_days" class="control-label">Balance Earned Leave Day/s</label>
								<input type="text" class="form-control" name="leave_balance" id="leave_balance" readonly required> 
							</div>							
						  </div>
						</div>						
						 <div class="row"> &nbsp; </div>
						 <div class="row">
						   <div class="col-lg-8  alert alert-success fade in">							
								<div class="form-group col-lg-4">
									<label for="no_of_days" class="control-label">Basic Pay(<?php //echo $this->currency_code(); ?>)</label>
									<input type="text" class="form-control" name="gross_salary" id="gross_salary" size="30" readonly required> 
								</div>	
								<div class="form-group col-lg-4">
									<label for="Deduction" class="control-label">TDS Deduction(<?php //echo $this->currency_code(); ?>)</label>
									<input type="text" class="form-control" name="deduction" id="deduction" size="30" readonly required> 
								</div>
								<div class="form-group col-lg-4">
									<label for="payment_amount" class="control-label">Payment Amount(<?php //echo $this->currency_code(); ?>)</label>
									<input type="text" class="form-control" name="payment_amount" id="payment_amount" size="30" required readonly> 
								</div>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-lg-11">
								<label for="subs_contact" class="control-label">Remarks</label>
								<textarea class="form-control" name="remarks" rows="4" col="60"> </textarea>
							</div>			
						</div>
						
						<div class="row">
							
							<div>
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Next </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button>  
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
<script>
$('document').ready(function(){
	$('#encash_date').datepicker();
	$("#applicant").change(function() {              
	   	$.post(
		    "<?php echo $this->url('leave', array('action' => 'getsalarydtl'));?>",
			{  
				employee_id: $(this).val(),
			},			
		function(data){
			console.log(data);
			$('#gross_salary').val(data.gross_salary);
			$('#deduction').val(data.PIT_deduct);
			var amount = parseFloat(data.gross_salary) - parseFloat(data.PIT_deduct);
			$('#payment_amount').val(amount);
		},
		"json"
	   );
	  	  
	   $('#empdtl').load("<?php echo $this->url('leave', array('action' => 'displayempdtl')); ?>/"+ $(this).val(), function() {       
           $("#empdtl").trigger('chosen:updated');
  	   });
	   $.post(
			"<?php echo $this->url('leave', array('action' => 'getleavedtls')); ?>",
			{
				emp_id: $(this).val(),
			},
			function(data){
				console.log(data);								
				$('#earned_bal').val(data.earned_bal);	
                var leave_bal =  $('#earned_bal').val() - $('#no_of_encashed_days').val();	
				$('#leave_balance').val(leave_bal);	
			},
			'json'
			);
     });     
	 
	$('#no_of_encashed_days').change(function() { 	
	  var leave_bal =  $('#earned_bal').val() - $('#no_of_encashed_days').val();
	  $('#leave_balance').val(leave_bal);	
	});  
	
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			applicant: {
					validators: {
						notEmpty: {
							message: 'Please select the Applicant.'
						}
					}
				},	
			earned_bal:{
				 validators: {
						greaterThan: {
							min: 34,
							message: 'Leave Balance should be minimum of 35 days'
						},
						notEmpty: {
							message: 'Please provide a value.'
						}
					}                					
			   },					
			   leave_balance: {
					validators: {
						greaterThan: {
							min: 4,
							message: 'Leave Balance should be minimum of 5 days'
						}
					}
				},				
				gross_salary: {
					validators: {
						notEmpty: {
							message: 'Provide gross_salary.'
						}
					}
				},
				deduction:{
					validators: {
						notEmpty: {
							message: 'Please Provide PIT Deduction.'
						}
					}
				},			
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('#encash_date').on('changeDate',function(){
		$('form').formValidation('revalidateField','encash_date');
	});	
});
</script>