<?php
/**
 * 
 * View -- of Hr/MasterController/addapptypeAction
 * 
 */
?><?php foreach($holidays as $holiday);?>
<form id="#form" method="post" action="<?php echo $this->url('leave', array('action' => 'editholidays')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> New Holiday</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body"> 
				<input type="hidden" id="id" name="id" value="<?php echo $holiday['id']?>">			
				<div class="form-group">
					<label>Date of Holiday:</label>
					<div class="date input-group" id="holi_date" data-date-format="yyyy-mm-dd">
						<input class="form-control" name="holi_date" id="holi_date" type="text" value="<?php echo $holiday['holi_date'];?>" placeholder="Date of Birth" >
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div> 		
				<div class="form-group">
					<label for="description" class="control-label">Description</label>
					<input type="text" class="form-control" name="description" id="description" value="<?php echo $holiday['description'];?>" size="30" placeholder="Description" > 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			holi_date: {
					validators: {
						notEmpty: {
							message: 'Please provide date.'
						}
					}
				},
				description: {
					validators: {
						notEmpty: {
							message: 'Please provide Decription.'
						}
					}
				},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('#holi_date').datepicker();
});
</script>