<?php
/**
 * 
 * View -- of Hr/MasterController/payheadAction
 * 
 */
	$this->headTitle($this->title);
?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Date</th>
					<th>Description</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
				$i = 1; 
				foreach ($holidays as $rows): ?>
					<tr class="<?php echo $class; ?>">
						<td><?php echo $i; ?> </td>
						<td><b><?php echo $rows['holi_date']; ?></b></td>
						<td><?php echo $rows['description']; ?></td>
							<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $rows['id']);?></td>
					<?php endif;?>
					</tr>
				<?php 
				$i++;
				endforeach;  
				?>                        
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>