<?php
/**
 * 
 * View -- of Sales/MasterpsController/serviceAction
 * 
 */

$this->headTitle($this->title);

?>
<?php echo $this->partial('hr/leave/partial.phtml', array('active' => 'leavebalancereport')); 
$year=date('Y');?>

<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form method="POST" action="<?php echo $this->url('leave', array('action' => 'leavebalancereport')); ?>" enctype="multipart/form-data" >    
						<div class="row">
							<div class="form-group col-lg-2">
								<label class="control-label" for="start_date">Start Date</label>
								<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $year.'-01-01';?>"  readonly>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="end_date">End Date</label>
								<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>"  required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-2">
								<label for="department" class="control-label">Department</label>
								<select class="form-control" id="department" name="department" data-placeholder="Select" onchange='this.form.submit()'>
									<option value="-1">All</option>
										<?php foreach($this->depObj->getAll() as $deps):?>
											<option value="<?php echo $deps['id']?>"<?php echo ($deps['id']==$data['department'])?'selected':'';?>>
											<?php echo $deps['department'];?></option>
										<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="region" class="control-label">Division/Region</label>
								<select class="form-control" id="region" name="region" data-placeholder="Select" >
									<option value="-1">All</option>
									<?php foreach ($region as $regions):?>
										<option value="<?php echo $regions['id']?>"<?php echo ($regions['id']==$data['region'])?'selected':'';?>>
										<?php echo $regions['region'];?>	</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="location" class="control-label">Location</label>
								<select class="form-control" id="location" name="location" data-placeholder="Select">
									<option value="-1">All</option>
									<?php foreach ($locations as $location):?>
										<option value="<?php echo $location['id']?>"<?php echo ($location['id']==$data['location'])?'selected':'';?>>
										<?php echo $location['location'];?>	</option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						<div class="form-group col-lg-3"></br>
								<div class="date input-group" >
								    <button type = "submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
								</div>
							</div>
					</form>
				</div>
			
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Region</th>
					<th>Location</th>
					<th>Designation</th>
					<th>Earned Balance</th>
					<th>Casual Balance</th>
					<th>Total Balance</th>
				</tr>
			</thead>
			<tbody>
				<?php
				 $total=0;	$no = 1;
						foreach($employee as $row):
							$employeeID =$row['id'];
							foreach($this->leavesObj->getBalanceReport($data,array('employee'=>$employeeID,'status'=>8)) as $leavede);
							$leaveencashMax = $this->leaveenObj->getMax('id',array('employee'=>$employeeID));
							$leaveencash =  $this->leaveenObj->getColumn(array('id'=>$leaveencashMax,'status'=>4),'encash_date');
							$encashyear = date('Y',strtotime($leaveencash));
							//print_r($encashyear);
							$leaveDate =$this->empObj->getColumn($employeeID, 'leave_balance_date');
							$leaveBal = $this->empObj->getColumn($employeeID, 'leave_balance');
							$empLocation = $this->empObj->getColumn($employeeID, 'location');
							$empolyeeMax = $this->emphisObj->getMax('id',array('employee'=>$employeeID));
							$appointment=$this->emphisObj->getColumn(array('id'=>$empolyeeMax),'type_of_appointment');
					
							if($appointment==14||$appointment==1){
								$empolyeeMax=$empolyeeMax;
							}
							elseif($appointment!=15){
								$empolyeeMax=$this->emphisObj->getMin('id',array('employee'=>$employeeID,'type_of_appointment'=>15));
								}
							if($leaveDate > 0 && $leaveBal > 0):
								$startDate = $leaveDate;
								$Balance = $leaveBal;
							else:
								$startDate = $this->emphisObj->getColumn(array('id'=>$empolyeeMax), 'start_date');
								$Balance = 0;
							endif;
							$empolyeeMax =  $this->emphisObj->getMax('id',array('employee'=>$employeeID));
							$empolyeeProbation =  $this->emphisObj->getColumn(array('id'=>$empolyeeMax),'type_of_appointment');
							$minYr = date('Y',strtotime($startDate));
							$minMonth = date('m',strtotime($startDate));
							$curYr = date('Y');
							$curMonth = date('m');
							$presentCasual =0;
							$presentEarned  =0;
							$casual = 0;  $earned = 0; 
							$i = 1;	$j = 1;		
							if($empolyeeProbation==14):$totalCasual = 5;else:$totalCasual = 10;endif;
						
							
							if(!empty($leavede)){
								for($curYear = $curYr; $curYear >= $minYr; $curYear--):			
									foreach($leavesObj->get(array('employee'=>$employeeID, 'ld.status'=>array(8))) as $leave):
										$startD = $leave['start_date'];
										$startYr = date('Y',strtotime($startD));
										$startMonth= date('m',strtotime($startD));							
										if($startYr == $curYear):
											if($minMonth<=$startMonth):
												if($leave['leave_type']==2):
													$casual += $leave['actual_leave_taken'];
													if($i == 1):
														$presentCasual = $casual;
													endif;// total casual leave used for till current year from given date															
													$i++;
												elseif($leave['leave_type']==3):
													$earned += $leave['actual_leave_taken'];//total earned leave used
													if($j == 1):
														$presentEarned = $earned;
													endif;// total casual leave used for till current year from given date															
													$j++;
												endif;	
											endif;
										endif;
									endforeach;											 						 
								endfor;	
								//endforeach;
								
							}	
							else{
								$usedcasual = 0;
									$CasualLeft = $totalCasual;
									$earned=0;
							}
							$total_years = $curYr - $minYr;
							$sub_total = 0;
							if($empolyeeProbation==14):$totCasual = 5;else:$totCasual = 10;endif;
							if($total_years > 0){
								$Bmonth = (12 - $minMonth);  //addition of 1 is to include the present month 
								$Amonth = $curMonth;
								$sub_total = $Bmonth + $Amonth;
								$Bcasual = round($totCasual);
								
								if($total_years == 1):
									$total_months = $sub_total;	
									if($empolyeeProbation==14):	$totCasual = 5;else:$totCasual = 10;endif;			
									$usedcasual = $casual - $presentCasual;
									$CasualLeft = $Bcasual - $usedcasual;					
									$totcasualBal = $totCasual - $casual;
									if($curYr==$encashyear):$totearnedBal = ($Balance + ($total_months * 2.5) - $earned)-30;else:$totearnedBal = $Balance + ($total_months * 2.5) - $earned;endif;
		 
								else:
									$YEAR = $curYr - $minYr - 1;
									$total_months = ($YEAR * 12) + $sub_total;							
									$totCasual = $Bcasual + 10 + ($YEAR * 10);
									$casualBefore = $casual - $presentCasual;
									$CasualLeft = $Bcasual + ($YEAR * 10) - $casualBefore;						
									$totcasualBal = $totCasual - $casual;
									if($curYr==$encashyear):$totearnedBal = ($Balance + ($total_months * 2.5) - $earned)-30;	else:$totearnedBal = $Balance + ($total_months * 2.5) - $earned;endif;							
								endif;
							}else{
								$total_months = $curMonth - $minMonth;
								$actCasual = $totCasual;
								$CasualLeft = 0;
								$actualCasual = round($actCasual);
								$totcasualBal = $actualCasual - $casual;
								if($curYr==$encashyear):$totearnedBal = ($Balance + ($total_months * 2.5) - $earned)-30;else:$totearnedBal = $Balance + ($total_months * 2.5) - $earned;endif;
								/*Breavemnt */
							}	
						  
						   $casual_bal = $totcasualBal;if($empolyeeProbation==14): $earned_bal=0;else:
						   $earned_bal = $totearnedBal + $CasualLeft;endif;
						   $casual_leave_used = $casual;
						   $earned_leave_used = $earned;
						   $leave_taken = $casual + $earned;
						   $total_bal = $earned_bal + $casual_bal;
						   
						   //print_r($beavement_leave_used);exit;
						   if($total_bal > 90){
								   $total_balance = 90;
						   }else{
								   $total_balance = $total_bal;
						   }
						   if($earned_bal > 90){
								   $earned_balance = 90;
						   }else{
								   $earned_balance = $earned_bal;
						   }
						   $balance_ttl=$casual_bal + $earned_bal;
						   if($balance_ttl > 90){
								   $balance = 90;
						   }else{
								   $balance = $balance_ttl;
						   }
						   $no_of_days = '';
					?>
					<tr>
						<td><?php echo $no++; ?> </td>
						<td><?php echo $row['full_name'];?></td>
						<td><?php echo $row['region'];?></td>	
						<td><?php echo $row['location'];?></td>	
						<td><?php echo $row['designation'];?></td>						
						<td><b><?php  echo $earned_balance;?><b></td>
						<td><b><?php  echo $casual_bal;?><b> </td>	
						<td><b><?php  echo $balance;?><b></td>						
					</tr><?php endforeach;?>
				</tbody>
		</table>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	//$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$('#region').on('change',function(){
		$.post(
			"<?php echo $this->url('employee', array('action' => 'getlocation'));?>",
			{
				regionId: $(this).val(),
			},
			function(data){
				$('select#location').html(data.location);
				$('select#location').trigger('chosen:updated');
			},
			'json'
		);
	});
});
</script>
