<?php
/**
 * 
 * View -- of Sales/MasterpsController/serviceAction
 * 
 */

$this->headTitle($this->title);

?>
<?php echo $this->partial('hr/leave/partial.phtml', array('active' => 'leavedailyreport')); ?>

<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form method="POST" action="<?php echo $this->url('leave', array('action' => 'leavedailyreport','id'=>$page)); ?>" enctype="multipart/form-data" >    
						<div class="row">
							<?php
							$current_date = date('Y-m-d');
							?>
							<div class="form-group col-lg-2">
								<label class="control-label" for="start_date">Current Date</label>
								<div class="date input-group" id="start_date" data-date="<?php echo isset($data['start_date']) ? $data['start_date'] : $current_date; ?>" data-date-format="yyyy-mm-dd" onChange='this.form.submit()'>
									<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo isset($data['start_date']) ? $data['start_date'] : $current_date; ?>" readonly>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
						</form>
				</div>
			<div class="col-lg-3 ">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2,$page);?>
				</div>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Location</th>
					<th>Designation</th>
					<th>Leave Type</th>
					<th>From Date</th>
					<th>To Date</th>
					<th>Duration</th>
					<th>Officiating</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; $total=0;
					foreach ($paginator as $row):
					?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<?php foreach ($this->employeeObj->get(array('e.id'=>$row['employee'])) as $emp);?>
						<td><?php echo $emp['full_name'];?></td>	
						<td><?php $location_id=$this->employeeObj->getColumn(array('id'=>$row['employee']),'location');
						echo $this->locationObj->getColumn(array('id'=>$location_id),'location');?></td>	
						<td><?php echo $emp['designation'];?></td>
						<td><?php echo $this->leaveObj->getColumn($row['leave_type'],'type');?></td>	
						<td><b><?php echo $row['start_date'];?></b></td>	
						<td><b><?php echo $row['end_date'];?></b></td>
						<td><b><?php echo $row['no_of_days'];?>&nbsp Days</b></td>						
						<td><?php if(empty($row['delegation'])):" ";else:echo $this->employeeObj->getColumn($row['delegation'],'full_name');endif;?></td>
						<td><?php echo $this->status($row['status']);?></td>	
					</tr><?php endforeach;?>
				</tbody>
		</table>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
