<?php
/**
 * 
 * View -- of Hr/EmployeeController/indexAction
 * 
 */
$this->headTitle($this->title);
 $minYear = date('Y', strtotime($minYear)); 
?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
			 <form id="#form" method="post" action="<?php echo $this->url('travel',array('action' => 'claim')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form> 
			</div>
		</div>
		
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
</div>
<div>
	<table class="table table-striped table-hover table-condensed" style="width:100%;" id="dataTables">
		<thead>
			<tr>
				<th>#</th>
                <th>No. (Date)</th>
				<th>Claim Date</th>
				<th>Details</th>
                <th>Actual Expense</th>
				<th>Estimated Expense</th>
				<th>Advance Requested</th>
                <th>Amount Claimed</th>
                <th>Status</th>
                <th>Action</th>
			</tr>
		</thead>
		<tbody>
			<?php $i = 1; foreach ($claim as $rows):?>
				<tr>
					<td><?php echo $i++; ?> </td>
                    <td><b><?php echo $rows['ta']; ?></b></td>
					<td><b><?php echo $rows['date']; ?></b></td>
					<td><?php echo $this->employeeObj->getColumn($rows['employee'],'full_name'); ?></td>
                    <td><?php echo $rows['actual_expense']; ?></td>
					<td><?php echo $rows['estimated_expense']; ?></td>
					<td><?php echo $rows['advance']; ?></td>
                    <td><?php echo $rows['amount_claim']; ?></td>
					<td><?php echo $this->status($rows['status']); ?></td>
					<td><?php echo $this->button(6,$rows['id'],'','979'); echo $this->button(6,"524-".$rows['id'],'','3');?></td>
					
				</tr>
			<?php 
			endforeach;  
			?> 
		</tbody>
	</table>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>

