<?php
/**
 * 
 * View -- of Hr/EmployeeController/addemployeeAction
 * 
 */
    $this->headTitle($this->title);
?>
<?php foreach($travel as $travels);
foreach($this->employeeObj->get($travels['employee']) as $emp);
$employeeUser = $this->userObj->getColumn(array('employee'=>$emp['id']), 'id');	?>
<div class="space-12"></div>
	<div class="row">
		<div class="col-lg-12"> 
			<div class="widget-box transparent">
				<div class="widget-header widget-header-smaller">
					<h4 class="widget-title blue bolder smaller"> Travel Authorization </h4>
				</div>
				<div class="widget-toolbar hidden-xs">
					<div class="btn-list">
						<span data-bs-toggle='tooltip' data-bs-placement='top' title='PDF Print'>
							<a class='btn btn-danger btn-xs' id="print">
							<i class="ace-icon fa fa-file-pdf-o bigger-120"></i></a></span>
					</div>
				</div>
				<div class="widget-body" id="print-content">
					<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
                                <li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										TA No. : <b class="red"><?php echo $travels['ta_no']; ?> </b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Applicant Details: <b class="red"><?php echo $this->employeeObj->getColumn($travels['employee'],'full_name') ; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Type of Travel: <b class="red"><?php if($travels['type']==1){echo "In Country";}else{echo "Ex Country";  } ?></b>
									</li>
									
									
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
								<li>
                                <i class="ace-icon fa fa-caret-right blue"></i>
									Date: <b class="red"><?php echo $travels['date']; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Estimated Travel Expense: <b class="red"><?php echo $travels['estimated_expense']; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Advance Requested : <b class="red"><?php echo $travels['advance']; ?></b>
									</li>
                                    <li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Purpose of Travel: <b class="red"><?php echo $this->purposeObj->getColumn($travels['purpose'],'purpose'); ?></b>
									</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<table class="table table-striped table-hover table-condensed table-bordered" style="width:100%; ">
								<thead>
									<tr>
										<th colspan=2>From</th>
										<th rowspan=2>Mode of Travel</th>
										<th colspan=2>To</th>
										<th rowspan=2>Halt</th>
										<th rowspan=2>Purpose</th>
									</tr>
									<tr>
										<th >Station</th>
										<th >Date</th>
										<th >Station</th>
										<th >Date</th>
									</tr>
								</thead>
								<tbody>
									<?php foreach($this->traveldetails->get(array('ta'=>$travels['id'])) as $row):?>
										<tr>
											<td><?php echo $row['from_station'];?></td>
											<td><?php echo $row['from_date'];?></td>
											<td><?php if($row['travel_mode']==1){echo "Land";}else{echo "Air";};?></td>
											<td><?php echo $row['to_station'];?></td>
											<td><?php echo $row['to_date'];?></td>
											<td><?php echo $row['halt'];?></td>
											<td><?php echo $row['purpose'];?></td>
										</tr>
									<?php endforeach;?>
								</tbody>
							</table>
						</div>
						<?php if($travels['advance']>0):?>
								<div class="row">
							<table class="table table-striped table-hover table-condensed table-bordered" style="width:100%; ">
							<tr>
								<td><b>Debit</b></td>
								<td><?php echo $this->subheadObj->getColumn($travels['debit'],'name');?></td>
								<td><b>Reference</b></td>
								<td><?php echo $travels['debit_ref']?></td>
							</tr>
							<tr>
								<td><b>Credit</b></td>
								<td><?php echo $this->subheadObj->getColumn($travels['credit'],'name');?></td>
								<td><b>Reference</b></td>
								<td><?php echo $travels['credit_ref']?></td>
							</tr>
						</table>
							<!-- 
								<div class="row"> 
                            <div class="col-lg-3">
								<div class="form-group">
									<label for="debit">Debit</label>
									<input class="form-control" name="debit" id="debit" value="<?php echo $this->subheadObj->getColumn($travels['debit'],'name');?>" readonly>
								</div>
							</div> 
							<div class="col-lg-3">
							<div class="form-group">
									<label for="debit_ref">Reference</label>
									<input type="text" class="form-control" name="debit_ref" id="debit_ref"  value="<?php echo $travels['debit_ref'];?>" readonly>
								</div>
							</div>
						</div>	
						<div class="row"> 
							<div class="col-lg-3">
								<div class="form-group">
									<label for="credit">Credit</label>
									<input class="form-control" name="debit" id="debit" value="<?php echo $this->subheadObj->getColumn($travels['credit'],'name');?>" readonly>

								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="credit_ref">Reference</label>
									<input type="text" class="form-control" name="credit_ref" id="credit_ref"  value="<?php echo $travels['credit_ref'];?>" readonly>
								</div>
							</div> 
						</div> -->
							<?php endif;?>
							<div class="col-lg-12" id="convert-tb2"><?php foreach($this->activityObj->get(array('process'=>523,'process_id'=>$travels['id'])) as $actvity):?>	
							<div class='underlined'>
									<b class="black"><?php echo $this->userObj->getColumn($actvity['author'],'name');?></b>&nbsp;<?php echo $this->status($actvity['status']);?> to: <b class="black"><?php echo strtoupper($this->userObj->getColumn($actvity['send_to'],'name'));?> on</b>&nbsp;<?php echo date('d-m-Y', strtotime($actvity['created'])); ?>
									<br>Remarks: <b class="black"><?php echo $actvity['remarks'];?></b>
							</div>
								<style>
									.underlined {
										border-bottom: 0.5px solid #000; /* Black underline */
										padding-bottom: 10px; /* Adjust spacing as needed */
										margin-bottom: 10px; /* Adjust spacing as needed */
									}
								</style>
							<?php endforeach;?></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-8"></div>
		<div class="col-lg-3" style="text-align: right"><?php
			$employeeUser = $this->userObj->getColumn(array('employee'=>$emp['id']), 'id');	
			$max_activity = $this->flowtransactionObj->getMax($column='activity', $where=array('application'=>$travels['id'],'flow'=>7));
				//echo'<pre>';print_r($max_activity);
			$current_flow = $this->flowtransactionObj->get(array('application'=>$travels['id'],'flow'=>7));
			foreach($current_flow as $flow);
			if($login_id  == $employeeUser && $travels['status']!=8 && $travels['status']!=6 && $travels['status']!=17 && $travels['status']!=21):?>
			<a data-toggle="modal" data-target="#modal" href="<?php echo $this->url('travel', array('action'=>'process', 'id'=>$travels['id'].'-'.'1'.'-'.$flow['id']));?>" class="btn btn-success"> 
			<i class="fa fa-check-square-o"></i> Apply  </a>								
			<button type="submit" value="1" name="cancel" class="btn btn-danger" onClick="return confirm('Are you sure to Cancel this note sheet?')"> 
			<i class="fa fa-times"></i> Cancel  </button>
			<a href="<?php echo $this->url('travel', array('action'=>'edittravel', 'id'=>$travels['id']));?>" class="btn btn-info"> 
			<i class="fa fa-pencil"></i> Edit </a>									
			<?php 
			elseif($login_id == $flow['role_id']):	
				$actions = explode('|', $flow['action']);
				for($i=0; $i < sizeof($actions); $i++):
					$buttons = $this->flowactionObj->get($actions[$i]);
					foreach($buttons as $button):?>
					<span data-bs-toggle='tooltip' data-bs-placement='top' title='<?php echo $button['action']; ?>'>
					<a data-toggle="modal" data-target="#modal" class="btn <?php echo $button['class']; ?>" href="<?php echo $this->url('travel', array('action' => 'process', 'id'=>$travels['id'].'-'.$button['id'].'-'.$flow['id'])); ?>">
						<i class="icon <?php echo $button['icon'];?>"></i><?php echo $button['action']; ?>
					</a></span>
			<?php endforeach;endfor;endif;?>						
		</div>
	</div>

<script type="text/javascript">	   
$(function(){
	 $('#print').gentcpdf({
		content: '#print-content',
		src:"<?php echo $this->url('print', array('action' => 'index'));?>",
		orentation:"P",
		size: 'A4',
	});
	
});
</script>


