<?php
/**
 * View -- of Hr/PayIncrementController/indexAction
 */
	$this->headTitle($this->title);
?>
<div class="row">
	<div class="col-lg-12">
		<i class="fa fa-flag green bigger-130"></i> New Basic Pay exceeds Maximum Pay Scale.<br>
		<i class="fa fa-flag red bigger-130"></i> Old Pay exceeds Maximum Pay Scale.
		<h3><?php echo $this->incrementObj->getColumn($increment_type,'increment_type');?></h3>
		<div>
			<table class="table table-striped table-hover table-condensed" style="width:100%;" id="trdetails_table">
				<thead>
					<tr>
						<th>#</th>
						<th>EmpID</th>
						<th>Employee</th>
						<th>Location</th>
						<th>Activity</th>
						<th>Position Level</th>
						<th>PayScale</th>
						<th>Old Pay</th>
						<th>Increment</th>
						<th>New Pay</th>
						<th>Action <label class="ace bolder blue">
						<input type="checkbox" id="checkAll" class="ace" />
						  &nbsp;<span class="lbl">Select All</span>
						</label></th>
					</tr>
				</thead>
				<tbody>
					<?php
						$i = 1; 
						if($increment_type != 4):
						$employees = $this->employeeObj->get(array('increment_type'=>$increment_type,'e.status'=>1));
						foreach ($employees as $emp):
							$positionlevels = $this->positionlevelObj->get($emp['position_level_id']);
							foreach($positionlevels as $level);
							$basic_pay = $this->paystructureObj->getColumn(array('employee' => $emp['id'], 'pay_head'=> '1'),'amount');
							if (is_numeric($basic_pay)) {
								$pay_increment = $basic_pay + $level['increment'];
							} else {
								$pay_increment = 0;
							}
					?>
						<tr <?php if($pay_increment > $level['max_pay']){ ?> class="success" <?php }elseif($basic_pay > $level['max_pay']){ ?> class="danger" <?php } else{} ?>>
							<td><?php echo $i++; ?> </td>
							<td>
								<?php echo $emp['emp_id']; ?>
							</td>
							<td><b><?php echo $emp['full_name']; ?></b></td>
							<td><?php echo $emp['location']; ?></td>
							<td><?php echo $emp['activity']; ?></td>
							<td><?php echo $emp['position_level']; ?></td>
							<td><?php echo $level['min_pay'].'-'.$level['increment'].'-'.$level['max_pay'];?></td>
							<td>
								<?php echo $basic_pay;?>
							</td>
							<?php if($increment_type == '1'):?>
								<td>
									<input type="hidden" value="<?php echo $emp['id']; ?>" name="employee_<?php echo $emp['id']; ?>" id="employee" />
									<input type="hidden" value="<?php echo $basic_pay;?>" name="old_pay_<?php echo $emp['id']; ?>" id="old_pay" />
									<input type="hidden" class="form-control" value="<?php echo $level['increment'];?>" name="increment_<?php echo $emp['id']; ?>" id="increment" />
									<input type="hidden" class="form-control" value="<?php echo $pay_increment;?>" name="new_pay_<?php echo $emp['id']; ?>" id="new_pay" />
									<input type="text" class="form-control" name="incrementM_<?php echo $emp['id']; ?>" id="incrementM" />
								</td>
								<td><input type="text" class="form-control" name="new_payM_<?php echo $emp['id']; ?>" id="new_payM" /></td>
							<?php else:?>
							<td>
								<?php echo $level['increment'];?>
							</td>
							<td>
								<?php echo $pay_increment;?>
							</td>
							<?php endif;?>
							<td>
								<input type="checkbox" name="increment_check[]" id="increment_check" value="<?php echo $emp['id']; ?>" <?php if($pay_increment > $level['max_pay'] && $increment_type!=1){ ?> disabled <?php } ?> > 
							</td>
						</tr>
					<?php 
						endforeach;
						endif;
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script>
	$("#checkAll").change(function () {
		$("input:checkbox").not("[disabled]").prop('checked', $(this).prop("checked"));
	});
		
	var tr_id =0;
	var parentObj = $('#trdetails_table');
	parentObj.wrap("<div style='overflow-x:scroll;margin-bottom:5px;'> </div>");
	parentObj.find("tbody tr").each(function(){
		$(this).attr('id',++tr_id);			
		$(this).find('div.chosen-search input').each(function(){
			$(this).addClass('ch-search');
		});
		$(this).find('div.chosen-container .chosen-drop').each(function(){
			$(this).css({'position':'relative'});
		});
		$(this).find(':input, :button').not('input.ch-search').each(function(){
			var old_id = $(this).attr('id');
			var new_id=(old_id.lastIndexOf('-') > 0)? old_id.substr(0, old_id.lastIndexOf('-')): old_id;
			$(this).attr('id',new_id+'-'+tr_id);
			$(this).addClass('tr-'+new_id);
		});				
		
		$(this).find('input.tr-incrementM').each(function(){
			var id = $(this).closest('tr').attr('id');
			$(this).bind('change', function(){	
				var new_pay = parseFloat($(this).val()) + parseFloat($('#old_pay-'+id).val());
				$('#new_payM-'+id).val(new_pay);	
			});
		});
	});
</script>


